### PR TITLE
LI: fixed intentions and fixes running within doctests

### LINKED ISSUE #6790: Editing in code blocks in doc comments completely broken
## Environment

* **IntelliJ Rust plugin version:** 0.3.140.3644-203
* **Rust toolchain version:** 1.49.0 (e1884a8e3 2020-12-29) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.3.2 (CL-203.7148.70)
* **Operating system:** Linux 5.9.13-arch1-1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Start here:

```rust
/// ```
/// # use repr_c_impl::layout::{Array, Type};
/// let x = Array {
/// };
/// ```
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Array<I: Layout> {
    pub element_type: Box<Type<I>>,
    pub num_elements: Option<u64>,
}
```

Execute the "Add missing fields action". Result:

```rust
/// ```
/// # use repr_c_impl::layout::{Array, Type};
/// let x = Array {
/// element_type: ,num_elements: };
/// ```
#[derive(CloBox::new(Type { })ne, Debug, Eq, NonePartialEq)]
pub struct Array<I: Layout> {
    pub element_type: Box<Type<I>>,
    pub num_elements: Option<u64>,
}
```

---

Start here with the cursor at the marked position:

```rust
/// ```
/// # use repr_c_impl::layout::{Array, Type};
/// let x = Array {
/// <cursor>
/// };
/// ```
```

Press tab. Result:

```rust
/// ```
/// struct Array {
    <cursor> /// 
/// }
/// ```
```

### PR DESCRIPTION
**Pull request by afetisov**
Closes #6790

Previously modification of injected doctest code was incorrectly handled, so that applying an fix or intention could result in corrupted code following the doctest. The reason was that modifications within a doctest run in their own injected editor, which wasn't correctly projected back into the containing file editor, but the offsets of changes were calculated relative to the whole file.

changelog: fixed intentions and type fixes applied with documentation tests

### CODE REVIEW

**Comment by afetisov** [comment]
This warrants a test, but I couldn't decide how and where to put it. Ideally we would want to run all annotation/fix/intention tests both within ordinary code and within doc comments, but that would probably significantly slow the testing with little gain. After all, there is no reason for injected code to behave differently from the usual one in the general case, and the edge cases are unlikely to be found simply by duplicating tests. I have tried to create a RsDoctestFixTest with a few test cases within org.rust.ide.annotator.fixes, but I couldn't understand how to make it treat the doctests as an injection. The test just treats it as text.

**Comment by afetisov** [comment]
Also please could someone take a look at my other PRs? #7483 #7474

**Comment by vlad20012** [comment]
Take a look at `RsEnterInLineCommentHandlerTest.doDoctestTestByText`. The magic is in `fileName = "lib.rs"` since only libs can have doctests.

**Comment by Undin** [comment]
Let's add tests before merge

**Comment by afetisov** [comment]
@vlad20012 Unfortunately that approach doesn't work. The problem is that when I try to test the code fences, I can only specify the behaviour with respect to the whole test file, but the editor fix tries to run in the injected editor. Specifically, I get the following diff:

```rust
extern crate test_package; fn __main() {
<error descr="Missing type for `const` item">const CONST = 1;</error>
```

vs 

```rust
/// ```
/// <error descr="Missing type for `const` item">const CONST/*caret*/ = 1;</error>
/// ```
struct Foo {
    var: i32,
    bar: i64,
    zar: [bool; 780],
}
```

in the pre-run code highlighting check when trying the expected test method 

```kotlin
checkFixByFileTree(
        "Add type i32",
        """
            //- lib.rs
            /// ```
            /// <error descr="Missing type for `const` item">const CONST/*caret*/ = 1;</error>
            /// ```
            struct Foo {
                var: i32,
                bar: i64,
                zar: [bool; 780],
            }
        """, """
            /// ```
            /// const CONST: i32 = 1;
            /// ```
            struct Foo {
                var: i32,
                bar: i64,
                zar: [bool; 780],
            }
            """,
    )
```

I don't see how I can tell the test fixture to use the same editor on both sides.

**Comment by Undin** [comment]
@afetisov I suppose `myFixture.setCaresAboutInjection(false)` before `checkFixByFileTree ` should solve described issue

**Comment by vlad20012** [comment]
Could you please it to the master instead of merging the master into it? There are rebasing instructions [here](https://github.com/intellij-rust/intellij-rust/pull/7060#issuecomment-823148179)

**Comment by vlad20012** [comment]
@afetisov thanks!

**Pull request closed without merging**
