### PR TITLE
Improve external ABI support

### PR DESCRIPTION
**Pull request by Undin**
Part of #886

changelog: Improve external ABI support:
- Parse any literal in ABI name position (including raw strings) and annotate non-string literals as invalid (in the same way as rustc does). 
    Screen Shot 2021-08-08 at 00 39 10
- Annotate invalid ABI names and experimental ABIs without the corresponding feature attribute
    Screen Shot 2021-08-08 at 00 39 34
- Provide competition for ABI names

### CODE REVIEW

**Review by mchernyavsky — APPROVED** [review]
LGTM

**Comment by Undin** [comment]
bors r=mchernyavsky

**Comment by Undin** [comment]
bors retry

**Review by vlad20012 — COMMENTED** [review]
LGTM

**Pull request merged**
