### PR TITLE
COMP: always place caret into the first arm in MatchPostfixTemplate

### PR DESCRIPTION
**Pull request by vlad20012**
An improvement to #7328: place the caret to the first arm after finishing the template

https://user-images.githubusercontent.com/3221931/124749393-d630a780-df2c-11eb-8f2d-ee0c3f282a35.mp4

### CODE REVIEW

**Review by Kobzol — APPROVED** [review]
This is great! I actually wanted to do something like this in numerous occasions before, but didn't know how to do it (didn't notice that templates contain a listener).

A similar template builder could also be used for the standalone `Fill remaining arms` quick fix.

Btw, the completion (or is it a template maybe?) inside pats seems to be quite wrong (I already stumbled upon it several times), and can severely mess up the template (e.g. `<template>_</template>` -> write `a` -> completion offers `assert!` -> template generates nonsense). But that's for another PR.

**Comment by vlad20012** [comment]
Well, it's possible to use macros in patterns, in theory...

**Comment by Kobzol** [comment]
Well.. :sweat_smile: In theory yes, but I have yet to see a macro being used inside a pattern :) I would rather just disable these kinds of completion here.

**Comment by Kobzol** [comment]
With the template listener, it would be nice to have a proper way of testing the template. Otherwise if template listener is used, it pretty much as to be combined with some `isUnitTestMode` check to fake the entered text in tests in order to test the listener behaviour.

**Comment by vlad20012** [comment]
I found how to make tests for templates. I'll explain it later (when I've done with the new API)

bors r=Kobzol

**Comment by vlad20012** [comment]
> Btw, the completion (or is it a template maybe?) inside pats seems to be quite wrong (I already stumbled upon it several times), and can severely mess up the template (e.g. `<template>_</template>` -> write `a` -> completion offers `assert!` -> template generates nonsense). But that's for another PR.

That was a live template. Fixed in #7547

**Pull request merged**
