### PR TITLE
ANN: annotate wrong return type for empty functions

### PR DESCRIPTION
**Pull request by Kobzol**
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5166

### CODE REVIEW

**Comment by Kobzol** [comment]
If we want to do this: https://github.com/intellij-rust/intellij-rust/issues/4833 then it would be consistent to mark the return type (although it might be missing in case of unit type, hmm).. Otherwise I'll change it to annotate the closing brace.

**Comment by Stzx** [comment]
@Kobzol I think you missed the `unimplemented!()`.

**Comment by Kobzol** [comment]
@stzx I'm sorry, I don't understand, what do you mean?

**Comment by Stzx** [comment]
@Kobzol  Oh, sorry. I didn't check it carefully. The original one already contains `unimplemented!()`.

**Comment by Kobzol** [comment]
@mchernyavsky What error type marking should be used? Only the return type, whole function, closing brace?

**Comment by mchernyavsky** [comment]
> @mchernyavsky What error type marking should be used? Only the return type, whole function, closing brace?

I prefer the closing brace. @Undin @vlad20012 What do you think?

**Comment by vlad20012** [comment]
This is the reason why the PR is not merged yet?  Oh...
I would not say that this is important. We can change it later. Let's make it somehow. `cargo check` already highlight a return type, so we won't make things worse if we do that too.
Btw #5552 can also be implemented by `}` brace highlighting

**Comment by Kobzol** [comment]
> This is the reason why the PR is not merged yet? Oh...

Yup :sweat_smile:

The closing brace is probably more general, since we cannot mark the return type if it's missing. Should I change it to the brace?

**Comment by vlad20012** [comment]
> Should I change it to the brace?

Oh :sweat_smile:
Okay, let's chenge

**Comment by Kobzol** [comment]
I changed it to the closing brace for empty functions. The `ChangeReturnTypeFix` is not currently offered for them. It would require non-trivial changes to it to make it work, and I don't think that you usually want to change the return type in situations when the function is empty. If you want the fix to work, let me know.

To solve #4833 with brace highlighting, it would have to only highlight the brace in the case of a trailing expr (and highlight return expressions for `return` statements, as it does now), which might be a bit confusing.

**Review by vlad20012 — APPROVED** [review]
bors r+

**Comment by vlad20012** [comment]
Hmm, I think I found a false-positive case:
```rust
trait FooBar {}
impl FooBar for () {}

fn foobar() -> impl FooBar {

}
```
bors r-

**Comment by Kobzol** [comment]
Oh, that's a very... interesting case :D Well, to support cases such as this one, I wonder if maybe the error annotation for empty functions should be moved into `TypeInferenceWalker`? Or should I just change the current implementation to use something like `TypeInference::combineTypes` to see if the result type is compatible with `()`?

**Comment by vlad20012** [comment]
`TypeInferenceWalker` looks more robust solution, but `impl Trait` is poorly supported even there. Let's just ignore `impl Trait`s at all for now

**Pull request merged**
