### PR TITLE
ANN: Don't suggest rustc's quickfixes with placeholders or unspecified applicability in batch mode

### PR DESCRIPTION
**Pull request by mchernyavsky**
Closes https://github.com/intellij-rust/intellij-rust/issues/5958.

### CODE REVIEW

**Comment by mchernyavsky** [comment]
@Undin Done.

**Review by Undin — COMMENTED** [review]
Hm, in both tests quick fixes from compiler are quite useful
I'd prefer to keep them.
Can we come up with more smart way to filter out incorrect quick fixes?
Is the original issue related to clippy only?

**Comment by mchernyavsky** [comment]
@Undin 

> Can we come up with more smart way to filter out incorrect quick fixes?

According to the [docs](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/enum.Applicability.html#variants) we should filter at least fixes with `HasPlaceholders` applicability.

> Is the original issue related to clippy only?

No. Clippy runs `cargo check` under the hood and shows its messages.

**Comment by mchernyavsky** [comment]
@Undin I have updated the PR. Now it filters quick fixes only if the inspection was ran in batch mode (i.e. via `Run External Linter` action or `Analyze | Inspect Code`).

**Comment by mchernyavsky** [comment]
Not sure how to test this because it looks like the tests require both `RsWithToolchainTestBase` and `RsInspectionsTestBase` classes.

**Comment by Undin** [comment]
@mchernyavsky ideally, we should reuse `RsAnnotationTestFixture` here since it was created exactly to be used in different classes (for example, `RsInspectionsTestBase` and `RsMultipleInspectionsTestBase`) and avoid code duplication but I'm not sure that it has all necessary things to check global inspection.
If it's hard to use it, I think we can create custom test class in this case and just copy necessary parts from `RsInspectionsTestBase`/`RsAnnotationTestFixture`

Also, looks like we don't have tests for global inspections yet. You can check how they are tested in IDEA repo

**Comment by mchernyavsky** [comment]
Closed by https://github.com/intellij-rust/intellij-rust/pull/8436.

**Pull request closed without merging**
