### PR TITLE
(INT) Navigate to implementation intention

### PR DESCRIPTION
**Pull request by Litarvan**
### Before

```rust
struct /*caret*/MyStruct {
}

impl MyStruct {
}
```

### After

```rust
struct MyStruct {
}

impl /*caret*/MyStruct {
}
```

**Note : This works even if the impl is in another file**

### CODE REVIEW

**Comment by Litarvan** [comment]
Oh and, little question, how do I "synchronise" my fork with the original repo ? I made an other remote origin and pulled, but it makes a merge commit and so all my commits are added to my new pull request :/

**Comment by alygin** [comment]
You need to synchronize your fork with the upstream repository before creating the branch for a new feature. Here's the description on how to do that: [Merging an upstream repository into your fork](https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/)

**Comment by alygin** [comment]
Hm, personally, I wouldn't expect this feature to be an intention. There's a special command _Go To -> Implementation(s)_ (_Navigate -> Implementation(s)_ in the main menu) and a hot key for that. Another way is [special gutter icons](https://github.com/intellij-rust/intellij-rust/pull/753).

**Comment by Litarvan** [comment]
Ok for the fork this is what i done, you're right i didn't see, i'll work on it

**Pull request closed without merging**
