### PR TITLE
TYPE: display notification panel when a file is not included in the module tree

### PR DESCRIPTION
**Pull request by Kobzol**
This PR adds a notification panel that warns about files which are not included in any module tree.
Currently the file has to be re-opened for the notification bar to update.

Corresponding issue: https://github.com/intellij-rust/intellij-rust/issues/1675

### CODE REVIEW

**Comment by vlad20012** [comment]
> Currently the file has to be re-opened for the notification bar to update.

Just add this code to `init` block:
```kotlin
subscribe(RUST_STRUCTURE_CHANGE_TOPIC, object : RustStructureChangeListener {
                override fun rustStructureChanged(file: PsiFile?, changedElement: PsiElement?) {
                    notifications.updateAllNotifications()
                }
            })
```

**Comment by vlad20012** [comment]
Btw #3426 can be solved by some action (see `createActionLabel`)

**Comment by Kobzol** [comment]
> Just add this code to `init` block:

Thank you, it works nicely :)

Considering https://github.com/intellij-rust/intellij-rust/issues/3426, what should the action do? Let's say there's a file `a.rs` in directory `b`. If I wanted to include this file in the tree, in theory it could be included either to `b/mod.rs`, `b.rs`, or `lib.rs`/`main.rs`/whatever the root file is called. So I need to get from the containing directory of the said file to a module root file. Is there an API for that? I tried using `toPsiDirectory` for the parent of the file, but I don't know how to get from a directory to anything Rust related (e.g. `RsElement`).

**Comment by vlad20012** [comment]
> what should the action do? Let's say there's a file a.rs in directory b. If I wanted to include this file in the tree, in theory it could be included either to b/mod.rs, b.rs, or lib.rs/main.rs/whatever the root file is called.

... or anywhere else via `#[path]` attribute or `include!()` macro, or it shouldn't included anywhere at all and it have '.rs' by accident, or it is code sample/test (like in IntelliJ Rust tests) etc etc etc

Yes, this is not trivial =) And I can't suggest anything for now.

I think this PR is finished. Thanks!
bors r+

**Comment by Kobzol** [comment]
Speaking of `include!`, this will probably show false positives for files included with it, at least until https://github.com/intellij-rust/intellij-rust/issues/1908 and similar are resolved, but there's probably not much that can be done about that. Thank you.

**Comment by vlad20012** [comment]
I don't think we should call it "false positive". This bar says that "analysis is not available", and it actually is not available :)

**Comment by Kobzol** [comment]
Indeed, the false positive part is actually `File is not included in module tree` :)

**Pull request merged**
