### PR TITLE
QDOC: quick doc improvements 2

### PR DESCRIPTION
**Pull request by Undin**
Improve quick doc and navigation info for structs, enums, traits, type aliases and associated types

### CODE REVIEW

**Comment by vlad20012** [comment]
bors r+

Thanks!

**Comment by Undin** [comment]
@vlad20012 Could you cancel bors? I want to add some tests

**Comment by Undin** [comment]
Thanks:)
I'll remove "WIP" from PR name when I finish:)

**Comment by Undin** [comment]
I've added tests as I had wanted, so this PR is ready for final review

**Comment by vlad20012** [comment]
bors r+

Thanks again :)

**Comment by Undin** [comment]
It seems bors is hanging again

**Comment by matklad** [comment]
bors r=vlad20012

**Pull request merged**
