### PR TITLE
ANN: highlight exit point better if last statement is loop

### PR DESCRIPTION
**Pull request by rrevenantt**
If last statement is loop, highlighting whole loop does not provide any additional information. This PR improves it.

### CODE REVIEW

**Comment by ortem** [comment]
Hello @rrevenantt, thank you for this PR and sorry for long waiting.

Your improvement of exit points highlighting is basically fine, but I'm not sure about `break` statements highlighting. Both Java and Kotlin don't highlight `break` as exit points:

Screenshot 2020-02-25 at 17 27 32 

but highlight the beginning of the corresponding loop:
Screenshot 2020-02-25 at 17 27 22


For comparison, your implementation:

Screenshot 2020-02-25 at 17 29 21


@Undin Do you have any thoughts about it?

**Comment by rrevenantt** [comment]
@ortem Done.

**Comment by ortem** [comment]
Thank you @rrevenantt!

bors r+

**Comment by Undin** [comment]
bors retry

**Comment by Undin** [comment]
@rrevenantt could you please rebase onto master?
bors fails to merge this PR for some reason

**Pull request closed without merging**
