### PR TITLE
Mark usages in doctests as "Test usages"

### PR DESCRIPTION
**Pull request by vlad20012**
| Before | After |
| - | - |
| image | image |
| image | image |

changelog: Mark usages in [doctests](https://doc.rust-lang.org/rustdoc/documentation-tests.html) as "Test usages"

### CODE REVIEW

**Comment by vlad20012** [comment]
@neonaot discovered that green highlighting doesn't work in CLion and PyCharm. That is, such highlighting does not exist in CLion at all.

**Comment by Undin** [comment]
@vlad20012 do I understand correctly that it's only about green highlighting and grouping in `Find Usages` tool window works as expected in all IDEs?

**Comment by vlad20012** [comment]
@Undin Yes, grouping works. At lease in CLion

**Pull request merged**
