### PR TITLE
CARGO: use the same project toolchain to get info about stdlib as project uses

### LINKED ISSUE #8517: Failed to parse the `edition` key
## Environment

* **IntelliJ Rust plugin version:** 0.4.164.4409-213
* **Rust toolchain version:** 1.60.0-nightly (27f5d830e 2022-02-02) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2021.3.3 (CL-213.6777.58)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.features.settings.gutter, org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
Project sync fails with this error:

```
Execution failed (exit code 101).
C:\Windows\system32\wsl.exe --distribution ubuntu --exec /bin/sh -c "export PATH=\"/home/matyas/.cargo/bin:$PATH\" && export RUST_BACKTRACE=short && export TERM=ansi && cd /home/matyas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test && /home/matyas/.cargo/bin/cargo vendor /mnt/c/Users/panstromek/AppData/Local/JetBrains/CLion2021.3/intellij-rust/stdlib/1.60.0-nightly-da0947d6a3255f7cde017d47d074aabb849e246a/vendor"
stdout : error: failed to parse manifest at `/home/matyas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.

stderr : 
```
This project runs in WSL

## Steps to reproduce

I am not sure how, but could it be that the directory override is not used by the sync command? My stable version is 1.49, but the project uses 1.60 nightly via directory override.

### PR DESCRIPTION
**Pull request by Undin**
Previously, the plugin used a toolchain related to stdlib source directory to get info about stdlib (dependencies, edition, etc.). And usually, it's a default toolchain from `rustup` point of view.
But if a user [overrides](https://rust-lang.github.io/rustup/overrides.html) toolchain for the project, the plugin didn't use it for stdlib that sometimes produced errors like https://github.com/intellij-rust/intellij-rust/issues/8517

Now, the plugin retrieves the actual toolchain name (from `rustup` point of view) and passes it to all commands used to get stdlib info

Fixes #8517

changelog: Use the project toolchain to retrieve info about stdlib. Previously, the plugin used the default toolchain for it that sometimes produced errors

### CODE REVIEW

**Comment by Undin** [comment]
@vlad20012 could you review changes in `UnitTestRustcCacheService`, please?
The main purpose is to have the ability to retrieve different info from external tools using the same types (like `String`)

**Review by mchernyavsky — APPROVED** [review]
bors r+

**Comment by jonhoo** [comment]
This code fails to take [custom toolchains](https://rust-lang.github.io/rustup/concepts/toolchains.html#custom-toolchains) which have the toolchain defined by a _path_, and not a name, into account. For example:

https://github.com/intellij-rust/intellij-rust/blob/bd51663e4ee3c35fbbb023f02b7a8a91fa6f661c/src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt#L111-L120

In practice it might mostly work out since a custom toolchain also has a `lib/`, but path-based toolchains won't work with `+` for example.

**Comment by jonhoo** [comment]
Huh, I take that back, apparently path-based toolchains _do_ work with `+`. In that case I think the problem here is mainly one of the code failing to document a case than any actually-wrong behavior 👍

**Pull request merged**
