### PR TITLE
FIX: parenthesize expressions where needed in Inline Value refactoring

### PR DESCRIPTION
**Pull request by Kobzol**
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7400

changelog: Parenthesize inlined expressions in Inline Value refactoring if they could produce invalid or semantically different code after performing the refactoring.

### CODE REVIEW

**Comment by vlad20012** [comment]
Please also take a look at `UnaryExpr`, `CastExpr`, `TryExpr` and `RangeExpr`, and to struct literals in `ForExpr`

**Comment by Kobzol** [comment]
Added more cases.

**Comment by vlad20012** [comment]
Oh, and also `while let` with a struct literal

**Comment by Kobzol** [comment]
And also `if let`. I wonder what have I missed this time :D

**Review by vlad20012 — APPROVED** [review]
bors r+

**Pull request merged**
