### PR TITLE
TY: block with bot expressions has bot type

### LINKED ISSUE #2006: Plugin incorrectly thinks that function returns ()
```Rust
fn a() -> i32 {
    if true {
        return 0;
    } else {
        return 6;
    };
}
```

While this code is bad style it is still valid, but plugin highlights this code as invalid: Function returns () instead of i32.

### PR DESCRIPTION
**Pull request by matklad**
closes #2006 

r? @vlad20012

### CODE REVIEW

**Comment by vlad20012** [comment]
Hmm, does it also fixes #1599?

**Comment by matklad** [comment]
Yep, added a test

bors r=vlad20012

**Comment by matklad** [comment]
bors r+

?

**Pull request merged**
