### PR TITLE
fix typo in RsDanglingElse.html

### PR DESCRIPTION
**Pull request by bmusin**
Hi. divided, not devided.

### CODE REVIEW

**Comment by mkaput** [comment]
Heh, https://en.wiktionary.org/wiki/devide#English :)

But, to be honest, I'd expect more *split* here instead. What do you think?

**Comment by bltnkl** [comment]
I'm sorry, don't quite understand what do you mean by "split"

**Comment by Undin** [comment]
@bltnkl I think @mkaput suggests to drop "divided" word at all and use "split" instead of it.

**Comment by Undin** [comment]
@bltnkl we need an electronic CLA for contributions: https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md#cla

After you sign the CLA, please add your name to
https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTORS.txt

**Comment by bmusin** [comment]
@mkaput, yes that's better, I changed commit.

**Comment by bmusin** [comment]
@Undin, submit outputs "Something is wrong".
[CLA](https://www.jetbrains.com/agreements/cla/)

**Comment by mkaput** [comment]
@bors r+

Thanks!

**Comment by Undin** [comment]
bors r=mkaput

**Pull request merged**
