### PR TITLE
Use the flat JetBrains badge

### PR DESCRIPTION
**Pull request by mchernyavsky**
Replaces [official JetBrains project](https://confluence.jetbrains.com/display/ALL/JetBrains+on+GitHub) with [official JetBrains project](https://confluence.jetbrains.com/display/ALL/JetBrains+on+GitHub)

### CODE REVIEW

**Comment by vlad20012** [comment]
But it is not flat...

**Comment by mchernyavsky** [comment]
image

**Comment by vlad20012** [comment]
Uh, we used Flat&squared previously, but now it is flat only. Ok!

**Pull request merged**
