### PR TITLE
Inline function refactoring improvements

### PR DESCRIPTION
**Pull request by SaarYogev**
Adding inline refactoring imnprovements, as asked in #5511 .

### CODE REVIEW

**Comment by Kobzol** [comment]
The inlining of parameters needs to be slightly more complex to handle arguments with side effects and complex patterns. I suggest that we leave it for another PR and this PR would focus only on the divergent return types, to make it easier for review.

```rust
fn test1() {
    let a = foo(bar()); // inline foo
    let a = bar() + bar() + bar(); // produced by PR
    let x = bar();
    let a = x + bar() + x; // should be produced if bar() has side effects (which it does, it's a function call)
}
fn test2() {
    let a = foo(&1 + 2); // inline foo
    let a = 1 + 2 + bar() + 1 + 2; // produced by PR
    let a = &1 + 2 + bar() + &1 + 2; // should be produced
}
fn foo(i: u32) -> u32 {
    i + bar() + i
}
fn bar() -> u32 {
    5
}

fn test3() {
    let x = foo2((1, 1)); // inline foo2
    let x = a + b; // produced by PR
    let (a, b) = (1, 1);
    let x = a + b; // should be produced (if a/b already existed in scope, their name should be changed)
}
fn foo2((a, b): (u32, u32)) -> u32 {
    println!("{} {}", a, b);
    a + b
}
```

**Comment by SaarYogev** [comment]
What exactly do you want in a separate PR? only the part about inlining function parameters correctly, or also the part about removing use statement when inlining a function from a different module?

**Comment by Kobzol** [comment]
Those are three separate things (exit point improvements, parameter inlining and `use` statement removal), so I think that they should be in 3 PRs. The `use` statement removal also needs to be more complex, for example currently it doesn't work if there are no callers of the method or if the `use` path of the function uses whitespace or is nested:
```rust
mod a {
  pub fn foo() {} /*inline*/
}

use a::foo; // not removed
```

```rust
mod a {
    pub fn foo() {} /*inline*/
    fn bar() {
        foo();
    }
}

use a:: foo; // not removed
use a::{foo]; // not removed
```


The `use`s of the inlined function should probably be found using the `ReferencesSearch` API (that's done already, but currently it only looks for calls to the function, it should also include `use`s).

**Comment by SaarYogev** [comment]
Will split, already have it split commit-wise for this case.  About using ReferenceSearch to remove the `use` statements:
I actually don't use `ReferenceSearch`, I compared them using text like so (`RsInlineFunctionProcessor:228`):
```rust
private fun removeFunctionUseStatements(function: RsFunction) {
    ReferencesSearch.search(function)
    caller.containingFile.children.filterIsInstance<RsUseItem>().forEach { useStatement: RsUseItem ->
        if (function.crateRelativePath?.trimStart(':') == useStatement.useSpeck?.text) {
            useStatement.delete()
        }
    }
}
```
ReferenceSearch seems like a better idea, but for some reason it doesn't work here:
```rust
usages.addAll(ReferencesSearch.search(function, projectScope).findAll())

usagesAsReference = usages.filter {
    it.element.ancestorOrSelf<RsCallExpr>() == null
        && it.element.ancestorOrSelf<RsMethodCall>() == null
}

usages.removeAll(usagesAsReference)
```
the `useSpeck` is the parent of one of the usages (debugged to check), but it doesn't get deleted, no idea why.

**Comment by Kobzol** [comment]
`usagesAsReference` is filtering only method/function calls, it needs to also include the `useSpeck` usages. Also there could be some postprocessing, for example `use a::{foo};` would be turned into `use a::{}`, but deleting it entirely is probably even nicer. Let's continue this discussion on the new PR.

**Comment by SaarYogev** [comment]
Opened #6003 #6004 #6005 for review, we'll continue dicussing there. I'll also add what's missing in each PR later today.

**Pull request closed without merging**
