### PR TITLE
RUN: Bench runner

### PR DESCRIPTION
**Pull request by mchernyavsky**
Closes https://github.com/intellij-rust/intellij-rust/issues/2488.

Adds a gutter icon to launch benchmarks in the same way as tests.

Edit Configuration Menu

Can be merged after https://github.com/intellij-rust/intellij-rust/pull/2963.

### CODE REVIEW

**Comment by vlad20012** [comment]
Hmmm, why do we store isTest, isCfg and now isBench inside functoin stub :thinking: :thinking: :thinking: @Undin ? Maybe some time ago we didn't stored attributes inside stubs... Anyway, we can remove it in another PR.

**Comment by amakeev** [comment]
I might be misreading the screenshot, but normally, all run-related actions are stacked under run button in IntelliJ Platform:

screenshot 2018-10-18 17 23 26

Do you think IntelliJ Rust could do the same (and also offer additional action for benchmarks such as debug)?

**Comment by mchernyavsky** [comment]
@amakeev, this line marker creates a regular run configuration.

Edit Configuration Menu

**Comment by mchernyavsky** [comment]
bors retry

**Pull request merged**
