### PR TITLE
RUN: cargo test for one function should use complete function path

### LINKED ISSUE #1499: Test one single function should run just the function's test
Consider a structure like following

```rust
#[cfg(test)]
mod tests {
    mod feature_a {
        #[cfg(test)]
        fn happy_path() {}
    }
    mod feature_b {
        #[cfg(test)]
        fn happy_path() {}
    }
}
```

Run `feature_a`'s `happy_path()` test should run just this test. Now the created configuration use just `happy_path` and then execute both of them.

PR is coming...

### PR DESCRIPTION
**Pull request by la10736**
Fix #1499

### CODE REVIEW

**Comment by la10736** [comment]
Sorry I've build it on an old fork ... I'll rebasing it ASAP

**Comment by Undin** [comment]
Test for IDEA 2017.1 fails because of it requires own fixture in `runconfig/producers/fixtures/2017.1`. Configuration structure has been changed in IDEA 2017.2 and old configurations for IDEA 2017.1 were moved in separate folder to support tests for both versions.

**Comment by la10736** [comment]
@Undin Thx for the tip

**Comment by la10736** [comment]
I hope that win my personal fight against fixtures and 2017.1 version test. If you use spaced functions test name fixture start by space and idea reject to refactor file name to insert a space ... Write test and fix code 20 minutes... make a correct PR 3h... But it was just my lack of knowledge.

**Comment by matklad** [comment]
Yeah, those file-based fixtures may be tricky, that's why we are now using "inline" fixtures more ofthen. However, they won't be as convenient for this particular flavor of tests :( 

Thanks!

bors r+

**Pull request merged**
