### PR TITLE
Add BLOCK_EXPR to USELESS_PARENS_EXPR

### PR DESCRIPTION
**Pull request by foriequal0**
Fixes: https://github.com/intellij-rust/intellij-rust/issues/9970
changelog: Fixes incorrect macro expansions when block expression is involved

### CODE REVIEW

**Review by vlad20012 — COMMENTED** [review]
Could you please also change `EXPANDER_VERSION` from 17 to 18?

**Review by vlad20012 — APPROVED** [review]
bors r+

**Comment by Undin** [comment]
@vlad20012 Do we have tests for this functionality?

**Comment by vlad20012** [comment]
@Undin There are `test literal expr is not wrapped into parens` and `test macro call expr is not wrapped into parens` tests in `RsMacroExpansionTest`, but other kinds of exprs are not tested (`PATH_EXPR`, `PAREN_EXPR`, `TUPLE_EXPR`, `ARRAY_EXPR`, `UNIT_EXPR` and now `BLOCK_EXPR`).

**Comment by Undin** [comment]
@foriequal0 Would you like to add test for your change (and maybe for other uncovered expression types)?

**Comment by foriequal0** [comment]
@Undin Sure! https://github.com/intellij-rust/intellij-rust/pull/9982

**Pull request merged**
