### PR TITLE
Reorganize CargoCommand Run configuration

### PR DESCRIPTION
**Pull request by matklad**
This simplifies `CargCommadConfiguration` a bit by switching from a reflection-based XMLSerializer to hand written serialization code, and by keeping stored data closed to the XML/GUI. As a bonus, "Include parent environment variables" now works properly.

This isn't ready for merging yet and will break tests under 2017.1. I'll come back to this after RustConf.

### CODE REVIEW

**Comment by matklad** [comment]
Part of https://github.com/intellij-rust/intellij-rust/issues/1632

**Comment by notriddle** [comment]
@matklad You're going to need to run it again. [We went down](https://bors.tech/pants-on-head-stupid/downtime/retrospective/2017/08/24/we-were-down/).

**Pull request merged**
