### PR TITLE
INT: add support for `extern` keyword in ImplementMembersFix

### LINKED ISSUE #3902: Wrong codegen with `extern fn` as function parameter
## Environment

* **Intellij-Rust plugin version:** v0.2.96.2123-183
* **Rust toolchain version:** 1.35.0-nightly
* **IDE name and version:** CLion 183.5429.37
* **Operating system:** Linux x64

## Problem description
When generating code for a `struct` `impl` through "Implement members",
`extern fn`s (i.e., function pointers) are not marked `extern`.

## Steps to reproduce
Use this code:
```rust
trait WithFunctionPtr {
    fn call(handler: extern fn(flag: bool));
}

struct UsingFunctionPtr;
impl WithFunctionPtr for UsingFunctionPtr {
    /* The line will have an error, use Alt+Enter > Implement members */
}
```
This generates:
```rust
fn call(handler: fn(bool)) {}
```
while it should be:
```rust
fn call(handler: extern fn(bool)) {}
```

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #3902

### CODE REVIEW

**Comment by t-kameyama** [comment]
I'm fixing, please wait a moment.

**Comment by t-kameyama** [comment]
PTAL

**Comment by mchernyavsky** [comment]
Traits can have default type parameters:

```rust
trait T<P = extern fn()> {
    fn call(handler: P);
}
struct S;
impl T for S {/*caret*/}
```

**Comment by t-kameyama** [comment]
PTAL

**Comment by t-kameyama** [comment]
PTAL

**Pull request merged**
