### PR TITLE
Restore compatibility with the IDEA 145.* (IDEA 15.*) branch

### PR DESCRIPTION
**Pull request by alexeykudinkin**

### CODE REVIEW

**Comment by matklad** [comment]
Ouch, I have a question actually :)

**Comment by alexeykudinkin** [comment]
Go ahead. Its gonna land in trunk in some way anyway.

**Comment by matklad** [comment]
Do we really need to support `15.0.4`? The latest minor version is `15.0.6`, and `15.0.4` does not include a security update (is this actually correct?).

With `15.0.6` (and I think 15.0.5 as well) plugin works without this changes.

**Comment by matklad** [comment]
Yep, `15.0.5` works just fine.

**Comment by alexeykudinkin** [comment]
We're not breaking compatibility with the previous versions until we're sure that no one (or almost no one) of our users are affected.

Especially in minor updates.

**Comment by alexeykudinkin** [comment]
Will trash this after complete migration to `15.0.6`.

**Comment by matklad** [comment]
Ok, then one other question: `15.0.3` in `build.gradle` looks kinda arbitrary. Why not `15.0.0` or `15.0.6` then? I would prefer to run local tests against `2016.1` and use CI to test for backwards compatibility .

**Comment by alexeykudinkin** [comment]
Yeah, my bad. Reverted `2016.1.2` as a default option.

**Comment by alexeykudinkin** [comment]
`15.0.3` has been chosen as the last one non-breaking version.

**Pull request merged**
