### PR TITLE
MACRO: expand multiple `lazy_static` definitions in the same call

### PR DESCRIPTION
**Pull request by msmorgan**
Adds macro expansion support for multiple `lazy_static` declarations in the same block.

I'm not sure how to go about writing a new test for this, since it seems that `RsResolveTestBase#checkByCode()` does not support resolving multiple symbols.

### CODE REVIEW

**Comment by vlad20012** [comment]
Please, add some tests to RsMacroExpansionResolveTest.kt

**Comment by msmorgan** [comment]
I added two tests that are pretty basic. Will they be adequate?

**Comment by vlad20012** [comment]
Oh, it's your first contribution here. Thank you!
Please, sign our CLA as described [here](https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md#cla) (the procedure consists of a couple of emails and clicks: no need to scan or print or snail-mail anything) and add your name to [contributor list](https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTORS.txt)

**Comment by msmorgan** [comment]
I went through the CLA process the other day. Do I need to upload the document I received?

**Comment by Undin** [comment]
@msmorgan No, it's enough just to sign it

**Comment by Undin** [comment]
Thanks!
bors r+

**Pull request merged**
