### PR TITLE
RUN: Ignore environment variables when comparing Cargo run configurations

### PR DESCRIPTION
**Pull request by mchernyavsky**
Fixes https://github.com/intellij-rust/intellij-rust/issues/6646.

### CODE REVIEW

**Review by ortem — APPROVED** [review]
The fix is probably OK. But I've just looked a bit into the `CompositeCargoRunConfigurationProducer` class and found out that `findOrCreateConfigurationFromContext` overloading is a bit strange and probably redundant. For example, `isSame` checked in `findExistingConfiguration` and then rechecked in `findOrCreateConfigurationFromContext`:
```Kotlin
val settings = findExistingConfiguration(context)
if (preferredConfig.configuration.isSame(settings?.configuration)) { ... }
```
In addition, `findOrCreateConfigurationFromContext` and `findExistingConfiguration` methods are rarely overloaded across IDEs and plugins. In contrast, `isConfigurationFromContext` is usually used to implement "similarity" checks.

I'm not sure it is important, but anyway, @mchernyavsky what do you think?

**Comment by ortem** [comment]
@mchernyavsky ping

**Comment by ortem** [comment]
Anyway, this should be merged of course.

bors r+

**Comment by Undin** [comment]
@mchernyavsky can we add tests for this? Something like: create a run configuration from some context, change some parameters, try to create a new run configuration from the same context and check if new configuration is really new or old one

**Pull request merged**
