### PR TITLE
DBG: Pretty-print HashMap/HashSet with MSVC LLDB

### PR DESCRIPTION
**Pull request by ortem**
Previously, our pretty-printers could not render `HashMap`/`HashSet` with MSVC LLDB (which does not contain Rust patches yet). The new implementation uses type lookup by name when template arguments are not recognized and should work without Rust patches.

Part of #5632.

changelog: Fix debug pretty-printers to render `HashMap`/`HashSet` with MSVC LLDB on Windows

### CODE REVIEW

**Review by Undin — COMMENTED** [review]
@ortem is it possible to set up pretty printers tests for Windows to verify such changes?

**Comment by ortem** [comment]
@Undin Yes, I implemented them: https://github.com/intellij-rust/intellij-rust/pull/7399

**Review by Undin — APPROVED** [review]
🔥 
bors r+

**Comment by Undin** [comment]
bors retry

**Pull request merged**
