### PR TITLE
DBG: Fix rendering of huge strings with LLDB

### LINKED ISSUE #9672: Debugger hangs with "Collecting data..." on huge string value
## Environment

* **IntelliJ Rust plugin version:** 0.4.183.4984-223-nightly
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) x86_64-apple-darwin
* **IDE name and version:** CLion 2022.3 EAP (CL-223.7401.10)
* **Operating system:** macOS 11.1

## Problem description
When showing huge string values (e.g. contents of a 100MB file), the debugger hangs with "Collecting data..." and the memory usage goes up.

## Steps to reproduce

```Rust
fn main() {
    let mut f = File::open("large_file.txt").unwrap();
    let mut contents: String = String::new();
    f.read_to_string(&mut contents).unwrap();
    println!(); // break
}
```

## Workaround
In `Preferences | Build, Execution, Deployment | Debugger | Data Views | Rust` settings, set `LLDB renderers` or `GDB renderers` to `No renderers`.

### PR DESCRIPTION
**Pull request by ortem**
Fixes #9672.

Now when rendering a summary of a string value, the LLDB pretty-printers do not load the entire contents automatically. Instead, the string is truncated to `target.max-string-summary-length` characters, which is set to 256 by default in CIDR debugger. When expanding the entire contents via `View` button, CIDR debugger increases `target.max-string-summary-length` to 1MB and triggers the pretty-printers again to load more content. The previous approach of reading a string from `Vec` character by character (`vec_to_string` function) was slow and memory-consuming, thus not suitable for retrieving 1MB of data. The new approach leverages a non-synthetic representation of `Vec` to read the memory directly. All the above applies to the following Rust types: `&str`, `String`, `OsString`, `OsStr`, `Path`, `PathBuf`, `CString`, `CStr`.

Note, the maximum string summary length can also be adjusted via LLDB Console or `.lldbinit` file: `settings set target.max-string-summary-length <SIZE>`.

**For QA**: this should be tested separately on Linux, macOS, and Windows.

https://user-images.githubusercontent.com/4854600/203348556-03995e85-6d6e-4764-8f83-b01bc44323d5.mov

changelog: Fix rendering of huge strings when debugging with LLDB

### CODE REVIEW

**Comment by Undin** [comment]
@ortem I suppose it should fix #9672, right?

**Comment by ortem** [comment]
@Undin That's right, thanks, I just forgot to mention it in the description

**Comment by MrGaribaldi** [comment]
Just curious, any timeline on when this will be tested and, hopefully, released? It is a major blocker for me, so really hope it can move forward to a release in the near future.

Thank you :)

**Review by mchernyavsky — APPROVED** [review]
bors r+

**Pull request merged**
