### PR TITLE
TY: tuple field type inference

### LINKED ISSUE #1269: No type is shown for tuple elements accessed by index
image

### PR DESCRIPTION
**Pull request by Undin**
Fixes #1269

### CODE REVIEW

**Comment by vasily-kirichenko** [comment]
Wow. That was fast :)

**Comment by vasily-kirichenko** [comment]
I have a long list of other snippets where types are not inferred. Should I create issues or you guys are already aware of all the restrictions?

**Comment by Undin** [comment]
I think @matklad can answer this question

**Comment by Undin** [comment]
But I personally think that it's a good idea to have list with all (maybe not all, but the most part) of language structs where type inference doesn't work

**Comment by matklad** [comment]
Looks good @Undin , but perhaps we can handle tuple structs here as well?

**Comment by matklad** [comment]
Nevermind, they are already handled here :)

**Comment by matklad** [comment]
@vasily-kirichenko we are aware that a lot of stuff just does not work, but having small isolated snippets would be super useful! I've created a meta-issue for this: https://github.com/intellij-rust/intellij-rust/issues/1272

**Pull request merged**
