### PR TITLE
Enable WSL support

### LINKED ISSUE #1171: What about using WSL Rust?
Hi. I'm trying to figure out how to use rustc & cargo from my WSL, where I installed rust, and works perfectly. In fact, I don't want to install Rust on Windows.
> https://medium.com/@bgourlie/cross-platform-development-on-windows-is-suddenly-awesome-da863a28fa1e

### PR DESCRIPTION
**Pull request by akainth015**
Fixes #1171 and continues #4797

### CODE REVIEW

**Comment by akainth015** [comment]
Thanks to @njasm for following this closely and making sure I don't leave this sitting for too long 😄

**Comment by imkow** [comment]
please merge this ASAP~~~

**Comment by akainth015** [comment]
Please do not merge; after doing some more testing, I have realized that some features like the Cargo run configuration do not run properly. I will continue to work on repairing them.

**Comment by bbeaupain** [comment]
Very excited for this feature, thank you for your hard work!

**Pull request closed without merging**
