### PR TITLE
HINT: Show type hints inside macro calls

### LINKED ISSUE #8214: The macro block does not show variable types
## Environment

* **IntelliJ Rust plugin version:**
v0.4.160.4261-212

## Problem description

In Macro's expr, the variable type does not predict and show ```  let v: i32 = 1; ```

But if you write it in a main function instead of a macro, this is normal.

```rust
#[macro_export]
macro_rules! ff {
    // for free spawn
    ($func:expr) => {{
        $func()
    }};
    }

fn main() {
     ff!(move || {
        println!("hi, I'm parent");
        let v = 1;
    });
}
```

Screenshot 2021-12-03 at 11 31 24

### LINKED ISSUE #8374: Type hinting in macro_rules bodies especially within the block token
## Environment

* **IntelliJ Rust plugin version:** 0.4.162.4321-212
* **Rust toolchain version:** 1.56.1 (59eed8a2a 2021-11-01) aarch64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.2.3 Ultimate Edition (IU-212.5457.46)
* **Operating system:** macOS 12.0.1
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.evaluate.build.scripts, org.rust.macros.proc

## Problem description
This is maybe not as much a bug as it is a feature request.
Lately I have started creating more macro_rules! and one of the useful tokens is block [block under metavariables](https://doc.rust-lang.org/reference/macros-by-example.html) 
I see that in this pull request [#4640](https://github.com/intellij-rust/intellij-rust/pull/4640) you added syntax highlighting to macro_rules bodies. 
It would be great if it was also possible to get type hinting in macros made with macro_rules! as it makes it
more convenient to use. Below I have included an image of a minimum example.

Screenshot 2022-01-08 at 01 38 02

If something is missing I will try to provide it as best as I can.
Thank you for making the rust plugin :)

## Steps to reproduce
In a new project type the code from the image above.

### PR DESCRIPTION
**Pull request by dima74**
Fixes #8214
Fixes #8374
Related: #9803
Depends on #10095

Add type hints inside function-like macro calls:

changelog: Show type hints inside macro calls

### CODE REVIEW

**Review by vlad20012 — APPROVED** [review]

**Comment by dima74** [comment]
bors r=vlad20012]

**Comment by dima74** [comment]
bors r=vlad20012

**Comment by dima74** [comment]
bors r=vlad20012

**Pull request merged**
