### PR TITLE
Bundled pretty-printer for LLDB: VecDeque support

### PR DESCRIPTION
**Pull request by ortem**
This PR adds `VecDeque` support to LLDB pretty-printers.

vd1
vd2

Merge after #3008.

### CODE REVIEW

**Comment by Undin** [comment]
I haven't reviewed it yet but at first glance, it seems that you add all code related to `Rc` and `Arc` in this PR.
Could you please leave changes related to `VecDec` only?

**Comment by ortem** [comment]
@Undin Done.

**Comment by Undin** [comment]
The current implementation doesn't take into account that `VecDeque` uses internal vector as ring buffer, i.e. `head` can be less than `tail` and vice versa.

If we run this code:
```rust
use std::collections::VecDeque;

fn main() {
    let mut deque = VecDeque::new();
    for i in 1..8 {
        deque.push_back(i)
    }
    deque.pop_front();
    deque.push_back(8);
    println!("{:?}", deque);
}
```
we get the following
image

**Comment by ortem** [comment]
@Undin Thanks for this note! I just cloned the original implementation, so I opened the corresponding [issue](https://github.com/rust-lang/rust/issues/55944).

**Pull request merged**
