### PR TITLE
INSP: navigate to created main function

### PR DESCRIPTION
**Pull request by Undin**
Improve quick fix introduced in #5481

### CODE REVIEW

**Comment by Undin** [comment]
CC @Stzx @vlad20012

**Comment by Stzx** [comment]
In fact, if the insertion symbol is inside the block, that would be great.
```rust
fn main() { /*caret*/ }
```

For the main function, we actually edit the method body more.

@Undin What do you think?

**Comment by Undin** [comment]
@Stzx good idea. Thanks!

**Pull request merged**
