### PR TITLE
PSI: split `RsBaseType` into 4 different PSI element types

### PR DESCRIPTION
**Pull request by vlad20012**
Namely, `RsPathType`, `RsUnitType`, `RsNeverType` and `RsInferType`

### CODE REVIEW

**Review by mchernyavsky — APPROVED** [review]
bors r+

**Review by Undin — COMMENTED** [review]
Should we increase `org.rust.lang.core.parser.RustParserDefinition#PARSER_VERSION`?

**Comment by vlad20012** [comment]
@Undin Oh yes, I incremented stub version instead :facepalm:

**Comment by vlad20012** [comment]
bors r=mchernyavsky

**Pull request merged**
