### PR TITLE
TY: infer Self type in assoc function

### LINKED ISSUE #1549: functions returning Self confuse intellij
```rust
    impl SApp {
        pub fn new() -> Self { SApp {  } }
        pub fn version(self) -> Self { self }
        pub fn get_name(&self) -> &str { "me" }
    }
    let m = SApp::new().version();
    println!("{:?}", m.get_name());
```

intellij doesn't know the type of 'm'. If 'new' and 'version' are changed to return 'SApp' everything works fine.

### PR DESCRIPTION
**Pull request by Undin**
Closes #1549

### CODE REVIEW

**Comment by vlad20012** [comment]
It was really extremely quickly,
Thanks a lot!

**Comment by Undin** [comment]
It is quite simple - need to start fix issue before it's written:D

**Pull request merged**
