### PR TITLE
Improve `RemoveTypeArguments`

### PR DESCRIPTION
**Pull request by Stzx**
Improve quick repair to remove redundant content instead of all content.

### CODE REVIEW

**Comment by Kobzol** [comment]
Hmm, this seems very similar to https://github.com/intellij-rust/intellij-rust/pull/5354 :-D

**Comment by Stzx** [comment]
@Kobzol Yes, it looks like we have implemented a similar function.

Do I need to close this PR? Or wait for other messages

**Comment by Kobzol** [comment]
I think that we should merge one of the PRs first and then try to rebase the other one on top to see what's different. There will probably be some things in your PR that aren't in mine and vice versa. @Undin what do you think?

**Comment by Undin** [comment]
> I think that we should merge one of the PRs first and then try to rebase the other one on top to see what's different. There will probably be some things in your PR that aren't in mine and vice versa. @Undin what do you think?

Yep, I agree. @mchernyavsky could you please look at #5354 first and after that at this PR as well?

**Comment by Kobzol** [comment]
https://github.com/intellij-rust/intellij-rust/pull/5354 has now been merged, which generates the merge conflicts. @Stzx could you please try to rebase on top of master to filter out things that have already been fixed by my PR?

**Comment by Stzx** [comment]
@Kobzol

 👌

**Comment by Stzx** [comment]
I checked the content of the conflict, maybe it is better to open a new PR for improvement?

**Comment by Kobzol** [comment]
I don't think that you need to open a new PR, you can just rename this one.

Btw I suspect that a plain rebase (i.e. rebase and then manually fix merge conflicts) might be too annoying in this case, maybe it will be easier to manually re-introduce your changes on top of my PR by hand.

**Comment by Stzx** [comment]
@Kobzol 

I submitted the change, but the branch name looks strange. 😃

**Pull request merged**
