### PR TITLE
RUN: Enable profiler for WSL 2 toolchains

### PR DESCRIPTION
**Pull request by mchernyavsky**
Closes https://github.com/intellij-rust/intellij-rust/issues/7857.

changelog: Enable profiler for WSL toolchains

### CODE REVIEW

**Review by ortem — APPROVED** [review]
LGTM (except for the fact that it would be better to refactor base classes in CLion codebase to avoid code duplicating in the future)

bors r+

**Comment by Undin** [comment]
@mchernyavsky @ortem what's the status of this PR?

**Comment by ortem** [comment]
@Undin It turned out that the profiler does not work properly on @mchernyavsky's machine with WSL 2. Originally, I only checked the code itself and the proper error message with my WSL 1 and assumed it was working fine with WSL 2. I've just asked @mili-l to check this with WSL 2 👌

**Review by mchernyavsky — COMMENTED** [review]
bors r=ortem

Thanks to @mili-l!

**Pull request merged**
