### PR TITLE
ANN: function args and return type must be Sized

### PR DESCRIPTION
**Pull request by Undin**
* check that types of function args and return type have `Sized` trait bound
* add quick fixes: convert to reference and convert to `Box`

### CODE REVIEW

**Comment by Undin** [comment]
I've found out that `ImplLookup.isSized()` implemented with `assembleCandidates` method is not convenient to use because we need `Sized` trait in our tests.
For these annotations, I use `Ty.isSized()` directly. Maybe drop `ImplLookup.isSized()` to have only one API for this goal?

**Comment by vlad20012** [comment]
@Undin as I remember, `ImplLookup.isSized()` and `Ty.isSized()` are not fully equivalent, but now it's so. You changed something before I merged the PR and I missed it =)
Then yes, now `ImplLookup.isSized()` is useless, I guess

**Comment by vlad20012** [comment]
Thanks!
bors r+

**Comment by Undin** [comment]
@vlad20012 yes, at the beginning `Ty.isSized()` didn't check supertraits of trait itself but when we decided to create special case for `Sized` trait in `ImplLookup.assembleCandidates()` I had to do it.

**Pull request merged**
