### PR TITLE
TYPE: Add visiblity for explict public in structure view

### LINKED ISSUE #1689: Public/Private visibility icons missing in Structure view
It seems commit 2df2b35885fcbc4aff40b1c4aaf10a62da09dfdc removed the private/public visibility icons from the Structure view.

Was this an intentional change?
The commit message is not clear if this is part of the simplification or not.
CC @matklad 

before:
before_visibility_icons_available

after:
after_visibility_icons_missing

### PR DESCRIPTION
**Pull request by farodin91**
Fixes #1689

### CODE REVIEW

**Comment by matklad** [comment]
LGMT! I wonder if we can somehow add a test for this though...

**Comment by farodin91** [comment]
I will look for it

**Comment by farodin91** [comment]
I add a basic test.

**Comment by matklad** [comment]
Thanks @farodin91 !

bors r+

**Pull request merged**
