### PR TITLE
ANN: Fix incorrectly providing `Add unsafe to function` in the main function

### PR DESCRIPTION
**Pull request by Stzx**
changelog:

Fixed: #8530

### CODE REVIEW

**Review by Undin — CHANGES_REQUESTED** [review]
Could you add a test to ensure that we don't provide the corresponding quick-fix for `main` function, please?
Also, it would be nice to have a test to check that we suggest the quick-fix for functions that look like a `main` (i.e. have the same signature and name) but are not `main` function (for example, function in library target)

**Comment by Stzx** [comment]
> Could you add a test to ensure that we don't provide the corresponding quick-fix for `main` function, please? Also, it would be nice to have a test to check that we suggest the quick-fix for functions that look like a `main` (i.e. have the same signature and name) but are not `main` function (for example, function in library target)

Oh, sorry

I forgot to mention that I intend to implement the detection for the [E0580](https://doc.rust-lang.org/error-index.html#E0580), which will of course include the corresponding tests.

**Comment by Undin** [comment]
> I forgot to mention that I intend to implement the detection for the [E0580](https://doc.rust-lang.org/error-index.html#E0580), which will of course include the corresponding tests. (but this will be implemented in the new PR)

But detection of `E0580` doesn't relate to `Add unsafe to function` quick-fix so I'd prefer to add suggested tests in this PR

**Comment by Stzx** [comment]
Sorry, I just misunderstood your meaning, the test case has been added.

**Review by Undin — APPROVED** [review]
Thanks!
bors r+

**Pull request merged**
