### PR TITLE
formatter: Use parameterized test case

### PR DESCRIPTION
**Pull request by Turbo87**
It is annoying to always manually have to add another test method for each test file pair that was added to the fixtures folder. This PR makes it easier by automatically detecting the test files and generating test cases for each one.

### CODE REVIEW

**Comment by matklad** [comment]
Will it be possible to run only a single test? In current solution I can place a caret on the test method and `Ctrl + Shift + f10` only it. It is a huge benefit in general, but it may be not that important for formatter tests.

Also we need a sanity check here ([like this](https://github.com/intellij-rust/intellij-rust/blob/master/src/test/kotlin/org/rust/lang/core/parser/RustCTRSTestCase.kt#L32)) to make ensure that tests are actually executed.

**Comment by Turbo87** [comment]
That is the one disadvantage of the solution. But since most of the time is spent on initializing the IDE instance there is actually not a lot of benefit in running only a single test. 

Sanity check should be possible by asserting that at least one test was discovered.

**Comment by matklad** [comment]
Yes, it possible to run a single test case, but not directly from the source code file.

I'm not sure about this change: adding two fixture files is more complicated then adding a single line to test, so this saves relatively few effort.  Running a single test becomes somewhat more difficult. But I like how this ensures that every fixture actually has a test attached to it. 

@alexeykudinkin what do you think?

**Comment by matklad** [comment]
> there is actually not a lot of benefit in running only a single test.

If you place a breakpoint in the formatter code then running only one test saves a lot of human time.

**Comment by Turbo87** [comment]
> > there is actually not a lot of benefit in running only a single test.
>
> If you place a breakpoint in the formatter code then running only one test saves a lot of human time.

weeeeell, you might be able to use a conditional breakpoint for that :wink:

**Comment by Turbo87** [comment]
> I'm not sure about this change: adding two fixture files is more complicated then adding a single line to test, so this saves relatively few effort.

you have to add the files in any case, but after doing that you don't have to navigate your way back to the  test class and add the method anymore.

I do see the disadvantages too, but I still think that overall this will make the testing simpler.

**Comment by matklad** [comment]
>I still think that overall this will make the testing simpler.
 
It makes writing a test easier and executing a test a bit harder. I'm ok with it as long as a sanity check is included. But let's reassign the issue to make a final decision =)

**Comment by Turbo87** [comment]
@matklad added the sanity check

**Pull request closed without merging**
