### PR TITLE
RUN: Get rid of `Show test tool window` and `Show stdout/stderr in tests (and disable test tool window)` options

### PR DESCRIPTION
**Pull request by mchernyavsky**

### CODE REVIEW

**Comment by idubrov** [comment]
What was the motivation for this removal? Being able to see test stdout was helpful in case test framework fails to start (for whatever reason) since in this case IJ test tool window is not helpful at all (it shows everything failed, but does not provide any output for the test framework).

**Comment by Undin** [comment]
@idubrov what version of rust do you use?
Stdout in tests should be shown since rust 1.39

**Comment by idubrov** [comment]
1.44.1; stdout is displayed for tests output, but in my case, sometimes the whole test framework fails (I use https://crates.io/crates/datatest).

This is what I get:
image

And with `--nocapture` it will be:
```
thread 'main' panicked at 'no test cases found for test 'xyz::xyz'. Scanned directory: 'xyz' with pattern '^(.*)\.input\.json'', /Users/idubrov/.cargo/registry/src/-e609b0c7dcf08590/datatest-0.6.3/src/runner.rs:192:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
...
```

**Comment by dokang89** [comment]
How can I see stdout when the test passed?

**Comment by mchernyavsky** [comment]
@dokang89 If you have rustc +1.39.0 test output should be shown in the window:

image

**Comment by dokang89** [comment]
> @dokang89 If you have rustc +1.39.0 test output should be shown in the window:
> 
I have rustc 1.43.0-nightly but it shows nothing
image
image
image

**Comment by mchernyavsky** [comment]
@dokang89 Can you please run this command from the terminal:
```
cargo test -- --show-output -Z unstable-options --format=json
```

**Comment by dokang89** [comment]
> @dokang89 Can you please run this command from the terminal:
> 
> ```
> cargo test -- --show-output -Z unstable-options --format=json
> ```
Here you are 

{ "type": "suite", "event": "started", "test_count": 1 }
{ "type": "test", "event": "started", "name": "test" }
{ "type": "test", "name": "test", "event": "ok", "stdout": "hello\n" }
{ "type": "suite", "event": "ok", "passed": 1, "failed": 0, "allowed_fail": 0, "ignored": 0, "measured": 0, "filtered_out": 6 }

**Pull request merged**
