### PR TITLE
INSP: Support usages in derive proc macros in unused imports inspection

### PR DESCRIPTION
**Pull request by dima74**
changelog: Support usages in derive proc macros in unused imports inspection

### CODE REVIEW

**Comment by Kobzol** [comment]
This does not solve this case, the false positive is still there:
```rust
use clap::{Clap, /*warning*/ValueHint};

#[derive(Clap)]
struct Opts {
    #[clap(long, value_hint = ValueHint::DirPath)]
    foo: String,
}

fn main() {}
```
Maybe it's because in `#[derive(Clap)]` `Clap` is parsed as a path, but in `#[clap(long, value_hint = ValueHint::DirPath)]` `ValueHint` is parsed as a compact TT?

**Review by vlad20012 — APPROVED** [review]

**Comment by dima74** [comment]
@Kobzol could you please check that you have `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` features enabled?

**Comment by Kobzol** [comment]
With these options there's no false positive, thanks! Didn't know that I need to enable them, sorry.

**Comment by dima74** [comment]
bors r=vlad20012

**Pull request merged**
