### PR TITLE
(ART): update file icons

### PR DESCRIPTION
**Pull request by mkaput**
Unfortunately I'm not skilled enough to make nice looking logo-based file icons (Rust logo looks ugly and very clumsy in small sizes; and I did old icons as bitmaps), so I opted to use shortcut-based style.

### CODE REVIEW

**Comment by alygin** [comment]
The current cargo file icons are way outdated. Maybe they should be revamped too?

**Comment by mkaput** [comment]
> The current cargo file icons are way outdated. Maybe they should be revamped too?

@alygin Do you have any idea, how it could look like? Current ones are just resized Cargo logos.

**Comment by alygin** [comment]
Given the trend, I think it should be something flat and resemble the official Cargo logo. I only have two ideas:

1) A flat full-face picture of the stack of boxes from the official logo. Sort of this:

cargo_ico_1

2) The standard IntelliJ file icon but with colors from the official logo. Something like this:

cargo_ico_2

A lock or a check-flag can be placed somewhere for the lock-files.

That's the limits of my design capabilities )

**Comment by mkaput** [comment]
1) is awesome!!! Please submit a PR! 😄

**Comment by alygin** [comment]
I will. But let's wait a bit, maybe someone will come up with something even more awesome )

**Comment by ice1000** [comment]
The screenshots on the website are using old icons. Maybe we should update those screenshots too.

**Pull request merged**
