### PR TITLE
T: convert tests names

### PR DESCRIPTION
**Pull request by Undin**
r? @matklad

### CODE REVIEW

**Comment by Undin** [comment]
I've was rather lazy so I haven't converted lexer tests :)

**Comment by matklad** [comment]
Ohhhh, excellent! 

bors r+

**Comment by Undin** [comment]
Looks like that `RsCargoCheckAnnotatorTest` doesn't work with latest rust version

**Comment by matklad** [comment]
Yeah, I've removed the now obsolete test in https://github.com/intellij-rust/intellij-rust/pull/2060.

Cargo check tests make me sad, they are very fragile :(

bors r+

**Pull request merged**
