### PR TITLE
:arrow_up: nightly rust

### PR DESCRIPTION
**Pull request by Undin**

### CODE REVIEW

**Comment by Undin** [comment]
Known issues:
* absence of libc sources in rust-src because of https://github.com/rust-lang/rust/pull/56092
* parser fails to parse `libstd/sys/sgx/waitqueue.rs` because of macro 2.0

**Comment by Undin** [comment]
@ortem Could you take a look at gdb pretty printers with latest nightly?

**Comment by ortem** [comment]
@Undin I've [fixed](https://github.com/intellij-rust/intellij-rust/pull/3449) the problem

**Pull request merged**
