### PR TITLE
IDE: do not recurse in `ImportingVisitor` in `RsAddImportCopyPasteProcessor`

### PR DESCRIPTION
**Pull request by Kobzol**
Related: #9664
Extracted from #9441

changelog: Improve performance of adding imports after paste.

### CODE REVIEW

**Review by dima74 — COMMENTED** [review]
We should also remove recursion from visitor in `createFqnMap` and change `RsRecursiveVisitor` to `RsVisitor`. But looks like it will break the code because of `startOffset` collision, so this PR should be merged after #9441

**Comment by Kobzol** [comment]
So shouldn't we just merge the original PR with all the changes applied at once?

**Comment by dima74** [comment]
> So shouldn't we just merge the original PR with all the changes applied at once?

The original PR is already quite complex, and the visitor changes are not as straightforward as I initially assumed (that's why I asked to extract it into separate PR - I wanted to merge it quickly), so for easier review let's keep this separate PR for the visitor recursion changes

**Comment by Kobzol** [comment]
Rebased.

**Comment by dima74** [comment]
It is more complicated unfortunately - we should also fix visitor used during copying. Actually I think it is worth to unite visitor logic during copy and paste - I opened #9978

**Pull request closed without merging**
