### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by Turbo87**
I've combined the new IntelliJ logo with the official Rust logo to make a logo for this plugin (and the `intellij-rust` GitHub org)

### CODE REVIEW

**Comment by matklad** [comment]
Awesome! I've been thinning about this just yesterday =)

I love the design. @atsky @alexeykudinkin what do you think?

**Comment by atsky** [comment]
I like it!

**Comment by alexeykudinkin** [comment]
@Turbo87 cool!

Though i believe we'd stick to the 2-letter abbreviation (`RT` for ex) alike other products do instead of using Rust's logo.

**Comment by Turbo87** [comment]
If you want to go down that road I would suggest using RS instead, similar to the file name extension.

**Comment by Turbo87** [comment]
any news on this?

**Comment by alexeykudinkin** [comment]
Not so much, yet. Wiil try to resolve by the end of the week.

**Pull request closed without merging**
