### PR TITLE
Disable inline macro use by default

### LINKED ISSUE #834: Formatter inlines [#macro_use] on crates and functions
Before:
```rust
#[macro_use(foo, bar)]
extern crate baz;

#[macro_use]
mod baa;
```

After formatter:
```rust
#[macro_use(foo, bar)] extern crate baz;

#[macro_use] mod baa;
```

While I couldn't find anything specific about this case in the [Rust style guide](https://aturon.github.io/style/whitespace.html), I does seem contrary to how examples are used in [the book](https://doc.rust-lang.org/beta/book/macros.html#scoping-and-macro-importexport).

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #834.

### CODE REVIEW

**Comment by mkaput** [comment]
Maybe delete whole feature if it's against RFCs, what do you think?

**Comment by matklad** [comment]
Yeah, let's just remove it altogether!

**Comment by johnthagen** [comment]
@mkaput @matklad I'm not super familiar with the code base, could you give me a short run down on what needs to be removed?

**Comment by matklad** [comment]
@johnthagen you need just to remove all usages of this constant: https://github.com/intellij-rust/intellij-rust/search?utf8=%E2%9C%93&q=INLINE_MACRO_USE_ATTR

**Comment by matklad** [comment]
Thanks!

**Pull request merged**
