### PR TITLE
Completion

### LINKED ISSUE #152: Add Autocomplete
Hello, there doesn't seems to be a ticket for autocomplete, so I will raise one.

Currently it would be great if intellij-rust would have a good autocomplete. I'm not sure if rust-racer is good enough for this job, but I think using it would greatly help this plugin to get more users.

### PR DESCRIPTION
**Pull request by matklad**
I'm not sure I have correctly squeezed this into existing resolve architecture.

`RustResolveEngine -> Resolver -> ResolveContext -> ResolveScopeVisitor -> NameProcessor` 

looks like a bit too much of indirection =)

fixes #152 

@atsky @alexeykudinkin please review

### CODE REVIEW

**Comment by alexeykudinkin** [comment]
Making completion a part of `RustResolveEngine` wasn't the best idea, it would definitely grow and its logic has nothing in common with the RRE (except that it targets resolved elements).

What was the motivation for going that way?

**Comment by matklad** [comment]
>its logic has nothing in common with the RRE 

* It does use the same `walk the tree up resolve scopes unitil mod boundary` logic. 
* [Docs](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/code_completion.html?search=completion) say somethinig along this lines.
* Go plugin shares logic for [completion](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/daa74f9feb26b0038317a2dca2be175c55f70be4/src/com/goide/completion/GoReferenceCompletionProvider.java#L127) and [reslove](https://github.com/go-lang-plugin-org/go-lang-idea-plugin/blob/dcff9d4cae91f3024359ea68726362822ae80e4b/src/com/goide/psi/impl/GoReference.java#L93)

I was thinking about slicing `RustResolveEngine.kt` into three files: 

* `walking the tree up` piece
* `resolve` piece
* `completion` piece

**Comment by alexeykudinkin** [comment]
When it comes to language processing pretty all stuff becomes looking like `walking the tree up resolve-scopes`. 

Bringing it to the RRE pulls along more clutter, than cleanliness desired since those two options (though generalisable) are loosely coupled, therefore, I believe completion deserves its own `RustCompletionEngine` (for ex).

P.P.S. Do not slice RRE up, or we'd end up making designated `fun`s for increment & decrement: there is (pretty) no other logic except walking up the scope-tree during resolve.

**Comment by atsky** [comment]
@alexeykudinkin, please take a look how completion implemented in Java (`PsiScopeProcessor`, `JavaCompletionProcessor`). It reuses code for reference resolving and I think It made same way in all language plugins. Completions and reference resolving does really similar thing so it stupid to implement it twice.

**Comment by alexeykudinkin** [comment]
First of all, i strongly disregard _blindly_ following the paved way. And second, i can hardly spot any code-reuse inside resolve facilities of the Java backend (please, check out `JavaCompletionUtil.processJavaReference`).

**Comment by alexeykudinkin** [comment]
In its most simplistic (auto) version it should go like this:

```kotlin
object RustCompletionEngine {

    private val PLACEHOLDER = "IntellijIdeaRulezzz"

    fun complete(ref: RustQualifiedReferenceElement): Collection<RustNamedElement> {
        val qual = ref.qualifier
        if (qual != null)
            return qual.reference.resolve()?.let {
                when (it) {
                    is RustResolveScope -> it.getDeclarations().flatMap { it.getBoundElements() }
                    else                -> null
                }
            } ?: emptyList<RustNamedElement>()

        val prefix = ref.nameElement?.let { it.text.removeSuffix(PLACEHOLDER) } ?: ""

        return enumerateScopesFor(ref)
                    .toList()
                    .flatMap { scope ->
                        scope.getDeclarations() .flatMap    { it.getBoundElements() }
                                                .filter     { it.name?.let { it.startsWith(prefix) } ?: false }
                    }
    }

}
```

**Comment by matklad** [comment]
>please, check out JavaCompletionUtil.processJavaReference

I think this is the [line](https://upsource.jetbrains.com/idea-ce/file/idea-ce-1731d054af4ca27aa827c03929e27eeb0e6a8366/java/java-impl/src/com/intellij/codeInsight/completion/JavaCompletionUtil.java?nav=15892:15937:focused&line=601) where completion hooks into common completion/resolve processing. 


>In its most simplistic (auto) version it should go like this:

This will not work correctly for local variables ([this](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/resolve/RustResolveEngine.kt#L372-L382) filtering logic) and will not complete imported named (`use foo::{bar, baz}`). This `is RustResolveScope` and `flatMap` bits are also look like a duplication of logic. 


On an unrelated note, should we really filter by ` it.startsWith(prefix)`? [Docs](https://upsource.jetbrains.com/idea-ce/file/idea-ce-1731d054af4ca27aa827c03929e27eeb0e6a8366/platform/core-api/src/com/intellij/psi/PsiReference.java?nav=4631:4775:focused&line=135) for `getVariants` say we should not do this.

**Comment by alexeykudinkin** [comment]
> I think this is the [line](https://upsource.jetbrains.com/idea-ce/file/idea-ce-1731d054af4ca27aa827c03929e27eeb0e6a8366/java/java-impl/src/com/intellij/codeInsight/completion/JavaCompletionUtil.java?nav=15892:15937:focused&line=601) where completion hooks into common completion/resolve processing. 

It don't. It don't hook up into resolving pipeline. And it should not. Check out [PsiReferenceExpressionImpl](https://upsource.jetbrains.com/idea-ce/file/idea-ce-1731d054af4ca27aa827c03929e27eeb0e6a8366/java/java-psi-impl/src/com/intellij/psi/impl/source/tree/java/PsiReferenceExpressionImpl.java?nav=stub:297): all it does trivial scope-traversal. 

Yeah, it wouldn't work with locals (though it wasn't assumed to do so). Problem with imports is due to the way `use-item` treats its bindings: i've fixed that in the trunk.

> On an unrelated note, should we really filter by it.startsWith(prefix)? Docs for getVariants say we should not do this.

We'd not, since there're a long pipeline of the stuff performing matches and brewing magic before spewing out your completed stuff (that's part is actually a bit of rocket-science), i've made it just for illustration purposes.

**Comment by matklad** [comment]
I will implement an alternative style of resolve for comparison then. 

But how should we deal with locals?

**Comment by matklad** [comment]
I'd like to bring this particular  piece from here to master: https://github.com/intellij-rust/intellij-rust/commit/68f090e07fd7b442910f0e428bec1f7397a90067

**Pull request closed without merging**
