### PR TITLE
WIP: Parse and evaluate #[cfg(...)] attributes during resolving

### PR DESCRIPTION
**Pull request by kumbayo**
This should not be merged yet as it is still work in progress.
I plan to submit this patches as a series of smaller PRs.

CC #1191
CC #461

### CODE REVIEW

**Comment by Pzixel** [comment]
@kumbayo any progress on this?

**Comment by kumbayo** [comment]
@Pzixel There has not been a lot of progress from my side lately :-(
But i rebased the patches on the latest master branch and they are somewhat working.
Please note that this branch does not support `cfg_if!` expansion. (For that please see #2601)

**Comment by vlad20012** [comment]
Btw now we can expand any macro, including `cfg_if!`

**Comment by kumbayo** [comment]
@vlad20012 Can you elaborate what you mean by
>  But it expandes to multiple definitions with different #[cfg] attributes, which we don't handle yet.
Do you have the result of such a cfg_if expansion?

The last time i had a quick look at cfg_if one of its helper macros was expanded wrong.
(But i have not checked for some time now.)

**Comment by vlad20012** [comment]
@kumbayo Yes, there is a bug in macro expansion causing cfg_if to exoands wrongly.
Previously I was sure that we can correctly expand any macro...

**Comment by elichai** [comment]
Any updates on this?
CC: https://github.com/intellij-rust/intellij-rust/issues/2561

**Pull request closed without merging**
