### PR TITLE
Improve AddStructFieldsFix for Vec

### PR DESCRIPTION
**Pull request by webdesus**
For more details #3168

### CODE REVIEW

**Comment by webdesus** [comment]
This pull request only includes Vec fixe. I can write it for String too if you do not mind.

**Comment by ortem** [comment]
Welcome to IntelliJ Rust! Please add your username to `CONTRIBUTORS.txt`.

**Comment by ortem** [comment]
Yes, you can do it for `String` in this PR too.

**Comment by ortem** [comment]
Please squash the first and the third commits into one

**Pull request closed without merging**
