### PR TITLE
DBG: provide debugger support outside of CLion

### LINKED ISSUE #2273: Ability to add breakpoints in .rs files
I work in AppCode and have installed the rust plugin for it. The syntax highlighting and checking seem to be working, but I can't set breakpoints in .rs files without editing the .xml file manually. Could we add this as a feature?

### LINKED ISSUE #3453: When will intellij idea support rust debugger ?
When will intellij idea support rust debugger ?

Or never ? !

### PR DESCRIPTION
**Pull request by Undin**
* works starting with 2020.1
* works only for Linux and macOS (Windows support is blocked by msvc toolchain support #4104)
* supported IDEs: IDEA Ultimate, AppCode and RubyMine
* requires [nativeDebug](https://plugins.jetbrains.com/plugin/12775-native-debugging-support) plugin for IDEA Ultimate (advertising of native debug plugin is a separate task #5201)
* only LLDB
* debugger is not bundled and need to be downloaded. Also, debugger binaries should be updated after IDE/native debug plugin update (see #5202 as possible improvement)

idea dbg 2020-04-06 16_54_05

Fixes #2273
Fixes #3453

### CODE REVIEW

**Comment by Undin** [comment]
Important scenarios/cases:
- `Rust` section in `Preferences | Build, Execution, Deployment | Debugger` shouldn't be shown in CLion
- Rust plugin update shouldn't remove downloaded lldb binaries. Can be checked via `Install plugin from disk` action, loading debuggers, installing plugin from disk again (it's the same as plugin update)
- Debugger should be updated after native debugger plugin updates that require new lldb version. It's quite hard to check right now because there isn't such versions of nativeDebug plugin currently, but we can emulate it. Just change any version in `versions.properties` in lldb directory (can be found in Rust section in `Preferences | Build, Execution, Deployment | Debugger` settings). It forces our plugin think that downloaded debugger binaries is outdated and should be updated. Note, the corresponding dialog should say about outdated debugger and update instead of the absence of debugger and downloading

**Comment by Undin** [comment]
Need to exclude `GDB renders` settings from `Preferences | Build, Execution, Deployment | Debugger | Data Views | Rust` panel

**Comment by lancelote** [comment]
Have tested it on Linux and macOS (taking into account the [comment above](https://github.com/intellij-rust/intellij-rust/pull/5200#issuecomment-612095182)). Everything works great for me, thank you for implementing it :+1:

**Comment by Undin** [comment]
bors r=mchernyavsky

**Comment by mchernyavsky** [comment]
bors retry

**Comment by vlad20012** [comment]
> RsDebuggerToolchainServiceTest
Hmm

**Comment by Undin** [comment]
bors r=mchernyavsky

**Comment by espdev** [comment]
> supported IDEs: IDEA Ultimate, AppCode and RubyMine

@Undin can I use this functionality in PyCharm Pro?

**Comment by Undin** [comment]
@espdev PyCharm Pro is not in supported IDEs listed in description so no. At least currently. We need nativeDebug plugin for but it's available only in IDEA Ultimate at this moment

**Comment by espdev** [comment]
@Undin Got it. Thanks.

**Comment by Undin** [comment]
I've created a separate issue about Rust debugger support in other JetBrains IDEs to see how if it's really needed

**Comment by Undin** [comment]
@espdev Could you specify what exactly do you want? Pure Rust debugging in PyCharm or cross debugging Rust and Python (similar to [this](https://youtrack.jetbrains.com/issue/CPP-5797) issue)

**Comment by espdev** [comment]
@Undin 

Rust/Python cross debugging is a very interesting feature! I plan to try Rust-Python integration (for example via PyO3) in the future, but currently I would like to be able to run regular Rust code under the debugger.

**Pull request merged**
