### PR TITLE
GRD: IDEA 2017.2, gradle 4.0.1 and kotlin api 1.1

### PR DESCRIPTION
**Pull request by Undin**
* update IDEA to 2017.2, gradle to 4.0.1, kotlin api to 1.1 
* drop support of IDEA 2016.3
* fix `RunConfigurationProducerTest` for IDEA 2017.2

NOTE:
* compatibility "hacks" related to IDEA 2016.3 are not fixed in this PR
* new compiler warnings appear because some APIs are deprecated in 2017.2

### CODE REVIEW

**Comment by Undin** [comment]
If someone knows better way to fix `RunConfigurationProducerTest `, I'll be glad to use it

**Comment by matklad** [comment]
@bors r+

Thanks a lot!

**Pull request merged**
