### PR TITLE
Support proc macro expander version 2

### LINKED ISSUE #10566: `rust-analyzer-proc-macro-srv` API breakage
I feel like we should inform you about this here as well, some months ago we started adding a version check to the proc-macro server so that we can add more functionality without breaking support for older servers as long as the client supports it (as our proc-macro server protocol is rather rigid). See the corresponding PR here https://github.com/rust-lang/rust-analyzer/pull/14070

The toolchain distributed `rust-analyzer-proc-macro-srv` component has this rolled out now on recent nightlies now (~1-2 week old as of posting). I think if a "client" (intellij in this case) does not know of this versioning things might start breaking for you as the server itself only supports the latest version. The only thing that really changed right now for version 2 is that the protocol now encodes the open and close span for groups separately, instead of assigning one to both.

(If you want we can keep this open after you've implemented this as a tracking issue for me to post whenever a new version gets added)

### LINKED ISSUE #10573: serde_with macro expand failed
## Environment

* **IntelliJ Rust plugin version:** 0.4.197.5408-231-nightly
* **Rust toolchain version:** rustc 1.72.0-nightly (37998ab50 2023-06-11)
* **IDE name and version:** 2023.1.3
* **Operating system:** Archlinux

## Problem description
image

it seems intellij-rust expand the `serde_as` attr macro failed, that make the IDE report `use std::net::Ipv4Addr` `DisplayFromStr` and `Deserialize` is unused

## Steps to reproduce
```rust
use std::net::Ipv4Addr;
use serde_with::{serde_as, DisplayFromStr};
use serde::Deserialize;

#[serde_as]
#[derive(Debug, Deserialize)]
pub struct Config {
    pub tun_name: String,

    #[serde_as(as = "DisplayFromStr")]
    pub local_ipv4: Ipv4Addr,
}
```

try this codes with `serde` and `serde_with` 3.0.0 version

### PR DESCRIPTION
**Pull request by vlad20012**
Fixes #10566, fixes #10573

changelog: Fix proc macro expansion with nightly Rust toolchain

### CODE REVIEW

**Comment by HTG-YT** [comment]
I tested this patch locally - there were a lot of IndexOutOfBounds exceptions.

Example:
```
java.lang.IndexOutOfBoundsException
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor214.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
	at com.intellij.util.ConcurrencyUtil.manifestExceptionsIn(ConcurrencyUtil.java:271)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$20(DaemonCodeAnalyzerImpl.java:1030)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.IndexOutOfBoundsException: Index (168) is greater than or equal to list size (165)
	at it.unimi.dsi.fastutil.ints.IntArrayList.set(IntArrayList.java:378)
	at org.rust.lang.core.macros.tt.FlatTreeBuilder.subtree(FlatTree.kt:129)
	at org.rust.lang.core.macros.tt.FlatTreeBuilder.write(FlatTree.kt:114)
	at org.rust.lang.core.macros.tt.FlatTree$Companion.fromSubtree(FlatTree.kt:93)
	at org.rust.lang.core.macros.proc.ProcMacroExpander.expandMacroAsTtWithErrInternal(ProcMacroExpander.kt:119)
	at org.rust.lang.core.macros.proc.ProcMacroExpander.expandMacroAsTextWithErr(ProcMacroExpander.kt:90)
	at org.rust.lang.core.macros.FunctionLikeMacroExpander.expandMacroAsTextWithErr(MacroExpander.kt:31)
	at org.rust.lang.core.macros.MacroExpansionSharedCache$cachedExpand$2.invoke(MacroExpansionSharedCache.kt:153)
	at org.rust.lang.core.macros.MacroExpansionSharedCache$cachedExpand$2.invoke(MacroExpansionSharedCache.kt:152)
	at org.rust.lang.core.macros.MacroExpansionSharedCache.getOrPut(MacroExpansionSharedCache.kt:97)
	at org.rust.lang.core.macros.MacroExpansionSharedCache.cachedExpand(MacroExpansionSharedCache.kt:152)
	at org.rust.lang.core.macros.MacroExpansionSharedCache.createExpansionStub(MacroExpansionSharedCache.kt:197)
	at org.rust.lang.core.resolve2.DefCollector.expandMacro(DefCollector.kt:431)
	at org.rust.lang.core.resolve2.DefCollector.expandMacrosInBatch(DefCollector.kt:415)
	at org.rust.lang.core.resolve2.DefCollector.access$expandMacrosInBatch(DefCollector.kt:41)
	at org.rust.lang.core.resolve2.DefCollector$expandMacrosInParallel$result$tasks$1$1$1.invoke(DefCollector.kt:401)
	at org.rust.lang.core.resolve2.DefCollector$expandMacrosInParallel$result$tasks$1$1$1.invoke(DefCollector.kt:400)
	at org.rust.openapiext.UtilsKt$computeInReadActionWithWriteActionPriority$success$1.invoke(utils.kt:374)
	at org.rust.openapiext.UtilsKt$computeInReadActionWithWriteActionPriority$success$1.invoke(utils.kt:373)
	at org.rust.openapiext.UtilsKt.runInReadActionWithWriteActionPriority$lambda$15(utils.kt:369)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:107)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at org.rust.openapiext.UtilsKt.runInReadActionWithWriteActionPriority(utils.kt:369)
	at org.rust.openapiext.UtilsKt.computeInReadActionWithWriteActionPriority(utils.kt:373)
	at org.rust.lang.core.resolve2.DefCollector.expandMacrosInParallel$lambda$14$lambda$13(DefCollector.kt:400)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedInterruptibleCallable.exec(ForkJoinTask.java:1461)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:436)
	at java.base/java.util.concurrent.ForkJoinTask.awaitPoolInvoke(ForkJoinTask.java:1034)
	at java.base/java.util.concurrent.ForkJoinPool.invokeAll(ForkJoinPool.java:2731)
	at org.rust.lang.core.resolve2.DefCollector.expandMacrosInParallel(DefCollector.kt:405)
	at org.rust.lang.core.resolve2.DefCollector.expandMacros(DefCollector.kt:317)
	at org.rust.lang.core.resolve2.DefCollector.collect(DefCollector.kt:85)
	at org.rust.lang.core.resolve2.FacadeBuildDefMapKt.buildDefMap(FacadeBuildDefMap.kt:41)
	at org.rust.lang.core.resolve2.DefMapsBuilder.doBuildDefMap(DefMapsBuilder.kt:121)
	at org.rust.lang.core.resolve2.DefMapsBuilder.access$doBuildDefMap(DefMapsBuilder.kt:19)
	at org.rust.lang.core.resolve2.DefMapsBuilder$buildDefMapAsync$1$1$1.invoke(DefMapsBuilder.kt:101)
	at org.rust.lang.core.resolve2.DefMapsBuilder$buildDefMapAsync$1$1$1.invoke(DefMapsBuilder.kt:100)
	at org.rust.openapiext.UtilsKt$computeInReadActionWithWriteActionPriority$success$1.invoke(utils.kt:374)
	at org.rust.openapiext.UtilsKt$computeInReadActionWithWriteActionPriority$success$1.invoke(utils.kt:373)
	at org.rust.openapiext.UtilsKt.runInReadActionWithWriteActionPriority$lambda$15(utils.kt:369)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:107)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at org.rust.openapiext.UtilsKt.runInReadActionWithWriteActionPriority(utils.kt:369)
	at org.rust.openapiext.UtilsKt.computeInReadActionWithWriteActionPriority(utils.kt:373)
	at org.rust.lang.core.resolve2.DefMapsBuilder.buildDefMapAsync$lambda$7(DefMapsBuilder.kt:100)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by vlad20012** [comment]
@HTG-YT Thank you! I pushed the fixed version

**Comment by HTG-YT** [comment]
Tested the new patch and everything works as intended. Thank you for working on this!

**Pull request merged**
