### PR TITLE
WIP: refactoring inline method

### PR DESCRIPTION
**Pull request by sohich**

### CODE REVIEW

**Comment by sohich** [comment]
@Undin @vlad20012, please help, I got some issue. 
My CI build failed because of using extension `RsExpr.suggestedNames()` defined in `RsNameSuggestions.kt`. Kotlin compiler gives an error because reference to this extension is unresolved. 
However, I am able to compile and launch my version locally. 
What might it be? Have you changed gradle build file may be?

**Comment by ice1000** [comment]
I'm very looking forward for intellij-rust to having this. What's the current status?

**Comment by sohich** [comment]
> I'm very looking forward for intellij-rust to having this. What's the current status?

Hi there! To be honest, work on this refactoring has benn freezed for a while. 
Gonna finish that soon - unit-tests and some improvements with type parameters substitution remain.

Thanks for your feedback, really appreciate it!

**Comment by vlad20012** [comment]
@sohich ping :)

**Comment by Undin** [comment]
Finished in #4460

**Pull request closed without merging**
