### PR TITLE
COMP: Suggest only methods from accessible traits

### LINKED ISSUE #9634: Code completion for undeclared crates
Please, why does the code completion system suggest methods from crates that **I don't use**??
I understand Rust does bring them as dependencies of dependencies of mine, but I do not declare them in my Cargo.toml, thus **I cannot use them**, so I think they should not be suggested at all. This makes the number of possible completions way bigger, but with **bogus** entries one cannot use, which makes the whole system more complex and cumbersome to use.

For example, I do not declare `itertools` in my Cargo dependencies, but its methods are still suggested:
image
You can see the list is huge, and I dare to say MOST of the suggestions I don't declare and can't use...

If I incorrectly end up using one of these methods, Rust of course doesn't like it, the trait isn't in scope:
image
If I do try to use it, Rust says it is undeclared.
image

So please, would it be possible to not give suggestions of methods for crates I don't declare? Pretty please?

<details><summary>Project dependencies in Cargo.toml</summary>

```toml
[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["macros","sync","fs","rt-multi-thread"], default-features = false }
reqwest = { version= "0.11", features = ["json"] }
bytes = "1.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = "1.0"
hex = "0.4"
toml = "0.5"
libchecksig = { version = "0.1", git = "https://github.com/cjdelisle/pkt-checksig", package = "libchecksig", branch = "main" }
blake2 = "0.9"
clap = { version = "3.2", features = ["derive"] }
clickhouse-rs = { git = "https://github.com/suharev7/clickhouse-rs", rev = "e40016bbc7546fb4d32340db074d3c66643cd5ca" }
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.6"
lazy_static = "1.4"
strum = { version = "0.24", features = ["derive"] }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres", "chrono", "offline"] }
env_logger = "0.9"
log = "0.4"
heck = "0.4"
futures-util = "0.3"
```

</details>

## Environment

* **IntelliJ Rust plugin version:** 0.4.181.4965-222
* **Rust toolchain version:** 1.64.0 (a55dd71d5 2022-09-19) aarch64-apple-darwin
* **IDE name and version:** CLion 2022.2.4 (CL-222.4345.21)
* **Operating system:** macOS 13.0
* **Macro expansion:** enabled

### PR DESCRIPTION
**Pull request by dima74**
Fixes #9634

changelog: Suggest in completion methods only from accessible traits

### CODE REVIEW

**Review by vlad20012 — COMMENTED** [review]
It filters out local traits as well :(
```rust
struct Foo {}
fn func(foo: &Foo) {
    trait Trait {
        fn method(&self) {}
    }
    impl<T> Trait for T {}
    foo.me/*caret*/
}
```

**Review by vlad20012 — APPROVED** [review]
bors r+

**Comment by hardskulls** [comment]
Is this fixed in 186 version of plugin?

**Comment by Undin** [comment]
@hardskulls no, it will be in 187 version. You can check the corresponding release version in `Milestone` section

**Pull request merged**
