### PR TITLE
PSI&PERF: use mixed AST where possible

### PR DESCRIPTION
**Pull request by vlad20012**
PSI is a set of Java/Kotlin interfaces describing a program structure (tree). Basically, these interfaces can be implemented in different ways. Actually, we use two different kinds of PSI implementations:
1. `ASTDelegatePsiElement`
```
+-----+         +-----+
| PSI | ------> | AST |
+-----+         +-----+
```
2. `StubBasedPsiElementBase`

```
+-----+         +-----+
| PSI | ------> | AST |
+-----+ \ OR    +-----+
         \
          \     +------+
           \ -> | Stub |
                +------+
```
 
But really there is a third option - **mix** PSI and AST in a single class/object:
```
+---------+
| PSI/AST |
+---------+
```

This is useful when a PSI element does not have a stub. In this case, additional AST object is not allocated, so we win in memory consumption, and the tree traversing will be fasted, so we win in CPU as well, so I decided to try it instead the first approach (with `ASTDelegatePsiElement`). To be honest, it seems like the first approach should never have been used. Its use brings only costs and no benefits. 

A PSI element can be mixed if it implements both `ASTNode` and `PsiElement` interfaces. This is already done in the platform class `CompositePsiElement`, so we can just extend in our PSI implementations (with no stubs). 

Ha-ha, "just". There is a problem - our PSI classes are generated by Grammar-Kit, so we have to teach it to generate such mixed implementations. Grammar-Kit's documentation says nothing about mixed AST, but I found the answer in its source ([1](https://github.com/JetBrains/Grammar-Kit/blob/962eb8c3e50a10b33d3df0e9db97744fe4c7aebc/src/org/intellij/grammar/generator/ParserGenerator.java#L282), [2](https://github.com/JetBrains/Grammar-Kit/blob/962eb8c3e50a10b33d3df0e9db97744fe4c7aebc/src/org/intellij/grammar/java/JavaHelper.java#L566)). Grammar-Kit can generate a proper implementation for mixed AST if it can figure out that a BNF rule produces mixed AST node. How Grammar-Kit figures it out: it reads `extends` property of the BNF rule (or the root property, in our case it is `extends='org.rust.lang.core.psi.ext.RsElementImpl'`), then it queries all superclasses of the class and tests their names against "com.intellij.psi.impl.source.tree.CompositePsiElement". If it succeeds, Grammar-Kit start thinking this rule uses mixed AST. This is it! Or not... Now you may wonder, how Grammar-Kit can ever get superclasses of a class by a name? And this is the most interesting part of the story! It tries to find a class by name (i.e. `org.rust.lang.core.psi.ext.RsElementImpl`) in its own classpath! It's important to stop here and think about it for a few seconds. Grammar-Kit is a program that reads `.bnf` (text) file as an input and produces a set of `.java` source files that then compiled by the Java compiler. But Grammar-Kit is itself written in Java! So it expects we (or whoever uses it) to compile some classes prior to Grammar-Kit invocation and then add them to its runtime dependencies (classpath) so it can read them in runtime and based on them decide on how to actually generate the stuff it generates. Oh...

 The problem here is that we can't compile, say, `org.rust.lang.core.psi.ext.RsElementImpl` class prior to Grammar-Kit invocation because `RsElementImpl` implementation is heavily depends on classes produced by Grammar-Kit, so it is a chicken-and-egg problem. 

I decided to solve this problem by introducing a separate gradle module `grammar-kit-fake-psi-deps` containing **FAKE** classes needed to Grammar-Kit to generate PSI properly. These classes partially mirrors our real basic PSI classes/mixins. They are not included into the plugin `.jar` binary and furthermore are not used anywhere except in Grammar-Kit.

Currently, I don't expect much performance benefits from this change because we use too lot of stubbed PSI. But I hope I will be able to remove the need to stub any `RsExpr`s in the future

### CODE REVIEW

**Comment by lppedd** [comment]
Someone should definitely update Grammar-Kit docs btw. This is a capability I had no idea existed.

**Comment by vlad20012** [comment]
I'm trying to simplify it in Grammar-Kir https://github.com/JetBrains/Grammar-Kit/pull/316

**Review by Undin — APPROVED** [review]
Looks ok as workaround
But it would be nice to merge the corresponding support into Grammar-Kit and get rid of this hack

**Comment by vlad20012** [comment]
Yep, I think we can merge this hacky version for now and then clean it up once the G-K fix is landed.

bors r+

**Pull request merged**
