### PR TITLE
RUN: Enable Code Coverage runner on non-nightly toolchains

### PR DESCRIPTION
**Pull request by mchernyavsky**
changelog: Enable Code Coverage runner on non-nightly toolchains

### CODE REVIEW

**Review by vlad20012 — APPROVED** [review]
bors r+

**Comment by vlad20012** [comment]
The issue is fixed in the nightly plugin. You can try it now (see [instructions](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly))

**Comment by MarinaKalashina** [comment]
@mchernyavsky Please add a 'to be documented' label

**Comment by MarinaKalashina** [comment]
Docs done https://plugins.jetbrains.com/plugin/8182-rust/custom-pages/docs/rust-code-coverage.html

**Pull request merged**
