### PR TITLE
ANN: correctly fill empty function call arguments

### PR DESCRIPTION
**Pull request by Kobzol**
See https://github.com/intellij-rust/intellij-rust/issues/6772#issuecomment-770784560 for an explanation why it is so complicated :D

Fixes: https://github.com/intellij-rust/intellij-rust/issues/6772

changelog: Correctly fill empty function call arguments.

### CODE REVIEW

**Comment by ortem** [comment]
Hi @Kobzol, I've found the current implementation doesn't work if I invoke `Fill missing arguments` after adding multiple parameters.

Consider adding multiple parameters to `foo`:
```Rust
fn foo() {}
fn main() {
    foo();
}
```
After `Change Signature`, I got this:
```Rust
fn foo(p0: i32, p1: bool, p2: char) {}
fn main() {
    foo(, , ); // invoke `Fill missing arguments`
}
```
After invoking `Fill missing arguments`, I got broken code:
```Rust
fn foo(p0: i32, p1: bool, p2: char) {}
fn main() {
    foo(0, false, ''), , );
}
```

**Review by ortem — CHANGES_REQUESTED** [review]
Hi @Kobzol, I've found the current implementation doesn't work if I invoke `Fill missing arguments` after adding multiple parameters.

Consider adding multiple parameters to `foo`:
```Rust
fn foo() {}
fn main() {
    foo();
}
```
After `Change Signature`, I got this:
```Rust
fn foo(p0: i32, p1: bool, p2: char) {}
fn main() {
    foo(, , ); // invoke `Fill missing arguments`
}
```
After invoking `Fill missing arguments`, I got broken code:
```Rust
fn foo(p0: i32, p1: bool, p2: char) {}
fn main() {
    foo(0, false, ''), , );
}
```

**Comment by Kobzol** [comment]
Hmm, if the call has no arguments and the comma directly follows the opening parenthesis, it parses like this :disappointed:
```rust
foo(,,);
```
image

Maybe it would be easier to change the parser after all?

**Comment by Kobzol** [comment]
@ortem Now that #7019 improved the parsing of function call arguments, I wonder if the error range of the `FillFunctionArgumentsFix` should change.

Currently, if there is not enough arguments, only the right parenthesis is annotated. This was done in https://github.com/intellij-rust/intellij-rust/pull/5612 to make the annotation more precise to let the user see quickly what is wrong:
```rust
fn foo(a: u32, b: u32, c: u32) {}

fn main() {
    foo(1<error>)</error>;
}
```

However, there is another case when this fix is applicable, and that's the situation where there are arguments, but they are "empty" (i.e. just whitespace/comments between commas):
```rust
foo(1 , , );
```
In this case it's probably not ideal to just mark the right parenthesis? Maybe we again go back to either marking the whole argument list or marking the individual commas?

**Comment by ortem** [comment]
@Kobzol I think marking the individual comma would be nice but not obligatory in this PR

**Comment by Kobzol** [comment]
Ok. I tried rebasing onto #7019 to reimplement the quick fix, but the parser is behaving a bit strangely, so I'll probably wait until #7019 is fully resolved and merged.

**Comment by ortem** [comment]
@Kobzol have you tried running `Generate Parser` Gradle task? If there are any problems with #7019 implementation, please mention them in the PR: probably they should be fixed before merging

**Comment by Kobzol** [comment]
I have regenerated the parser just to be sure. To be honest, I'm not sure if it's the parser or if I'm doing something wrong. I pushed a WIP version of my code (a simplified version that build a new argument list instead of modifying the original one).

When I run `FillFunctionArgumentsFixTest::test ufcs self value`, in `FillFunctionArgumentsFix:98` a new argument list is being created out of two expressions (`S` and `0`). However, the newly created argument list will have no expressions and its text simply equals `(`. CC @vlad20012

**Comment by vlad20012** [comment]
Some tests in #7019 are failed. I'll take a look

**Comment by Kobzol** [comment]
Great, after the parser fix it now works perfectly! There are still some implementation questions though. I have basically two implementations working, one is creating a new argument list and then replacing the old one, and another one inserts the missing arguments directly into the old list.

Creating a new argument was already done in the original fix implementation, it has simpler code and it also "normalizes" the argument list, e.g. in the case when the user inserted too many commas:
```rust
fn foo(a: u32, b: u32, c: u32) {}

foo(1,,,3);
v
foo(1, 0, 0);      // replace
foo(1, 0, 0,,3);  // insert
```
But it also removes any potential formatting/comments in the argument list (the original fix did the same). Is that OK?

Also for the error annotation, I would need something similar as in https://github.com/intellij-rust/intellij-rust/pull/6745. Basically I want to enable the quick fix in the whole argument range, but I only want to mark the end parenthesis with an error annotation. But I had some problems with that (https://github.com/intellij-rust/intellij-rust/pull/6745#issuecomment-797706690).

**Comment by Kobzol** [comment]
I rebased over master and changed the highlighting. Now the whole argument range offers the quick fix, but only the right parenthesis gets error annotation to reduce visual clutter. The changes in parsing also add additional error highlight to successive commas, which gets us the best of both worlds I think.

Can you take another look please @ortem? :) If you like it, I'll re-bless tests.
fill-arguments

**Review by ortem — APPROVED** [review]
LGTM now. @Kobzol thank you!

**Comment by Kobzol** [comment]
Great! Rebased over master and reblessed tests.

bors r=ortem

**Pull request merged**
