### PR TITLE
[WIP] Implement a basic parsing and handling for cargo's local index

### PR DESCRIPTION
**Pull request by Jezza**
Basic implementation for #2757

### CODE REVIEW

**Comment by Kobzol** [comment]
Just for some inspiration, this is a VSCode plugin that does something similar: https://github.com/serayuzgur/crates/pull/77/files. A similar approach is also in this crate https://github.com/LucianoBestia/cargo_reg_local

**Comment by vlad20012** [comment]
I am very wary of such solutions. 
1. Uses `git` binary. Git is not mandatory for our plugin. 
2. Relies on cargo index internal structure. 

Ideally, Cargo should just provide a subcommand with for us.

**Comment by Kobzol** [comment]
What about using crates.io as a fallback and only use the `git` + internal index poking strategy as a best effort strategy if `git` is available? (at least until Cargo provides a proper way to query the DB).
I refactored the crate resolving slightly in https://github.com/intellij-rust/intellij-rust/pull/5439, it could be used to add another (git) resolver. We can also add some caching for the API resolver.

**Comment by Kobzol** [comment]
Superseded by https://github.com/intellij-rust/intellij-rust/pull/6390.

**Pull request closed without merging**
