### PR TITLE
Fix some deprecation and unstable API usage warnings

### PR DESCRIPTION
**Pull request by Undin**
Use new API or suppress warnings if it's not possible or unclear to fix the warning

Related to #6737

### CODE REVIEW

**Comment by Undin** [comment]
@vlad20012 could you look at https://github.com/intellij-rust/intellij-rust/blob/b840c8dd9dc8f0d0692571baae711e9f381f9960/src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt#L454 and fix it if possible

**Comment by Undin** [comment]
@mchernyavsky Could you look at `CargoBuildTaskRunner` and fix all usages of deprecated API if possible, please?

**Comment by mchernyavsky** [comment]
@Undin Done.

**Pull request merged**
