### PR TITLE
Enable using the Rust plugin with a toolchain in WSL

### PR DESCRIPTION
**Pull request by akainth015**

### CODE REVIEW

**Comment by njasm** [comment]
Is this the code that will allow us to tell CLion to use cargo binary and rust toolchain installed in the WSL?

**Comment by akainth015** [comment]
Yes, my apologies for deleting my fork of this repository but the code was completely functional

**Comment by njasm** [comment]
@akainth015 Great thanks mate! looking forward to see this one move forward and land.

I would be more than glad to help out test this feature, but i don't believe we'll have that change without that fork of your. anyway, thanks!

**Comment by njasm** [comment]
@akainth015 why did you closed this one?

**Comment by akainth015** [comment]
Thanks for following this closely! I'm fixing a few issues remaining and 7 tests that aren't passing just yet.

I intend to open a pull request for this tomorrow once I have a bit more time to smooth it out, and will make sure to tag you in it. If you happen to have the time, I would appreciate it if you could take a look over it and check if there's anything obvious you happen to catch.

**Pull request closed without merging**
