### PR TITLE
RES: Support resolve of attribute and bang proc macros in new resolve

### PR DESCRIPTION
**Pull request by dima74**
Support resolve of attribute and bang proc macros in [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217)

Depends on #6317

### CODE REVIEW

**Review by Undin — COMMENTED** [review]
@dima74 tests?

**Comment by dima74** [comment]
@Undin there already exists `RsProcMacroResolveTest` (will be enabled in CI for new resolve in #6317). Do you think we need specific proc macro tests for new resolve?

**Comment by Undin** [comment]
@dima74 I usually expect that the feature and its tests are located in the same PR. AFAIK @lancelote also uses our tests to identify what was done and what's need to be tested

**Comment by dima74** [comment]
@Undin ok, so lets first merge #6317 which will add `@IgnoreInNewResolve` annotation to proc macro tests, and then I will update this PR to remove `@IgnoreInNewResolve` annotation from part of proc macro tests, so it will clear which tests are supported by this PR

**Review by vlad20012 — APPROVED** [review]
Well, let's remove `@IgnoreInNewResolve` from `RsProcMacroResolveTest`?

**Comment by dima74** [comment]
bors r=vlad20012

**Pull request merged**
