### PR TITLE
Handle 8-bit and 24-bit ANSI color escapes in console

### PR DESCRIPTION
**Pull request by mchernyavsky**
Fixes https://github.com/intellij-rust/intellij-rust/issues/1261 (already fixed?)
Closes https://github.com/intellij-rust/intellij-rust/issues/1630 (?)
Fixes https://github.com/intellij-rust/intellij-rust/issues/1966
Fixes https://github.com/intellij-rust/intellij-rust/issues/2463
Fixes https://github.com/intellij-rust/intellij-rust/issues/1842 (does it work as expected?)

Thanks @kumbayo for [this](https://github.com/intellij-rust/intellij-rust/issues/1966#issuecomment-445550757) comment!

TODO:
* Fix issue with white color on Windows
#### Update

Looks like a Rustc issue.

macOS Mojave:
```
^[[0m^[[1mFor more information about this error, try `rustc --explain E0369`.^[[0m
```

Windows 10:
```
^[[0m^[[1m^[[38;5;15mFor more information about this error, try `rustc --explain E0369`.^[[0m^M
```

As you can see, on Windows, Rustc prepends `^[[38;5;15m` control sequence to some chunks of text, which forces console use white color for the foreground. This is a problem, as the default background in IDEA is also white.

Not sure how to fix it (and whether to do it at all). The user can configure color mapping in the console (`Preferences > Editor > Console Scheme > Console Colors > ANSI Colors`).

### CODE REVIEW

**Comment by kumbayo** [comment]
Can you maybe leave a small comment at `RsKillableColoredProcessHandler` which explains why this ANSI code mapping is necessary?

**Comment by Undin** [comment]
bors retry

**Comment by mchernyavsky** [comment]
bors retry

**Pull request merged**
