### PR TITLE
New approach to generate info about compiler features

### PR DESCRIPTION
**Pull request by Undin**
Previously, info about compiler features was generated by `updateCompilerFeatures` Gradle task. The task downloaded some files from rustc codebase and extracted necessary info from the corresponding macro calls using regular expressions.
It worked, but such approach heavily depends on implementation of the corresponding macro calls

The new approach uses the same rustc code (downloaded by build scripts during build process) and compiles them using rustc itself. It allows us not to depend on the structure of the macro calls (since they are processed by the compiler itself) and just use generated info.
As a result, this new code contains info not only about compiler features (similar to the Gradle task) and also info about builtin attributes (but it's not used yet by the plugin)

To compile code downloaded from compiler, there are some additional crates manually copied from `rustc` repo and cropped not to depend on unused part of the compiler and minimize dependency on compiler code

To generate compiler features using this new way, you need to have nightly compiler and run `Generate compiler features` run configuration

### CODE REVIEW

**Review by mchernyavsky — APPROVED** [review]
bors r+

**Review by mchernyavsky — APPROVED** [review]

**Comment by Undin** [comment]
bors r=mchernyavsky

**Pull request merged**
