### PR TITLE
FMT: Add an option to use rustfmt instead of build-in formatter

### PR DESCRIPTION
**Pull request by mchernyavsky**
Closes https://github.com/intellij-rust/intellij-rust/issues/5191. c.c. #1087

In this implementation, `Rustfmt` can be used **only** when formatting the **whole file** by: 
1. `Code | Reformat Code` (`Ctrl + Alt + L`) action **without text selection**
2. `Code | Reformat File ...` (`Ctrl + Alt + Shift + L`) action with `Whole file` option

E.g. `Rustfmt` can't be used when committing to git with `Reformat code Before Commit` option (it doesn't clear how to achieve this).

By default, the built-in formatter is still ALWAYS used. `Rustfmt` can be enabled in `Settings | Languages & Frameworks | Rust | Rustfmt`.

NB: rustfmt has an unstable option to restrict reformatting to specific sets of lines (https://github.com/rust-lang/rustfmt/issues/3397).

### CODE REVIEW

**Comment by mchernyavsky** [comment]
@Undin Done.

**Comment by Kobzol** [comment]
Just wondering, isn't the option "reformat with rustfmt on save" a bit weird after this change? Maybe it could be changed to "reformat on save" to be ortogonal with selecting the used formatter?

**Comment by vlad20012** [comment]
> Just wondering, isn't the option "reformat with rustfmt on save" a bit weird after this change? Maybe it could be changed to "reformat on save" to be ortogonal with selecting the used formatter?

I think the option should be eventually removed in favor of something like [save action plugin](https://plugins.jetbrains.com/plugin/7642-save-actions)

**Review by vlad20012 — APPROVED** [review]
🎉🎉🎉
I updated the PR description

bors r+

**Comment by vlad20012** [comment]
bors retry

**Pull request merged**
