### PR TITLE
CI&MACRO: expand proc macros on Apple Silicon machines

### PR DESCRIPTION
**Pull request by Undin**
Part of #6908

changelog: Support [procedural macro](https://doc.rust-lang.org/reference/procedural-macros.html) expansion on Apple Silicon machines. Note:
- you should use `aarch64-apple-darwin` toolchain to make procedural macro expansion work
- the proc macro expansion is still disabled by default. To turn it on, enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` [experimental features](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features)

### CODE REVIEW

**Comment by Undin** [comment]
@ortem I've added the latest commit temporarily just to save plugin zip archive in artifacts. Could you please check that proc macro expansion works on Apple Silicon machines with it?

**Review by ortem — CHANGES_REQUESTED** [review]
Discussed in person with @Undin that the implementation should be changed because `CpuArch.isArm64()` does not work as expected on Apple M1:  `System.getProperty("os.arch")` is `"x86_64"` in virtualized JVM

**Comment by Undin** [comment]
> Discussed in person with @Undin that the implementation should be changed because CpuArch.isArm64() does not work as expected on Apple M1: System.getProperty("os.arch") is "x86_64" in virtualized JVM

Found out that it's not an actual issue because:
- it works even if we try to use x86 native helper on Apple Silicon machine
- JetBrains IDEs for Apple Silicon uses arm64 version of jdk that correctly returns os architecture.

The actual problem was using `x86_64-apple-darwin` toolchain instead of `aarch64-apple-darwin`. That led to an error in `dlopen`

**Pull request merged**
