### PR TITLE
GRAM: add trait aliases parsing support

### PR DESCRIPTION
**Pull request by lundibundi**
This adds basic parsing support for trait aliases (https://github.com/rust-lang/rfcs/blob/master/text/1733-trait-alias.md).

Though it doesn't integrate type inference/type resolution/method resolution/import support and etc for them. I have wanted to implement those but based on the code I've seen (`RsTraitOrImpl`, `TyTypeParameter`, `TraitImplSource`) it is tightly bound to the `RsTraitItem` type which has its own Stub and is therefore not an easy target to substitute with `RsTraitAlias` and I'm not sure which abstraction should be added for that purpose.

Another way would be to modify `RsTraitItem`'s BNF to also cover Trait aliases though that may be harder to maintain as they have some strict distinction (i.e. you cannot write `impl` blocks for Trait aliases, they cannot have Associated types)

### CODE REVIEW

**Comment by vlad20012** [comment]
:+1: LGTM
Just one thing: please, write yourself to contributors.txt and sign our CLA as described in [contributors.md](https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md#cla)

**Comment by lundibundi** [comment]
@vlad20012 done.

**Comment by mchernyavsky** [comment]
bors retry

**Comment by mchernyavsky** [comment]
bors r=vlad20012

**Pull request merged**
