### PR TITLE
ANN: Check E0117 "Trait impls orphan rules"

### PR DESCRIPTION
**Pull request by dima74**
Related: #6308, #6776, #886

changelog: Detect [E0117](https://doc.rust-lang.org/error-index.html#E0117) compiler error

### CODE REVIEW

**Review by ortem — APPROVED** [review]
bors r+

**Comment by dima74** [comment]
bors r=ortem

**Comment by dima74** [comment]
bors retry

**Comment by dima74** [comment]
bors retry

**Pull request merged**
