### PR TITLE
TOML: suppress completion in Cargo.toml based on JSON scheme

### LINKED ISSUE #9116: Crate version autocompletion: suggest the last stable version by default, not {}, "", or alphas
## Environment

* **IntelliJ Rust plugin version:** 0.4.176.4773-221-nightly
* **Rust toolchain version:** 1.62.0 (a8314ef7d 2022-06-27) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.1.2 (CL-221.5787.29)
* **Operating system:** Linux 5.10.0-16-amd64
* **Macro expansion engine:** new
* **Name resolution engine:** new
* **Additional experimental features:** org.rust.cargo.emulate.terminal

## Problem description
I was adding dependencies to Cargo.toml in this way:
- Type the beginning of crate name, e.g. `future` and press Ctrl+Space
- Select the correct crate, e.g. `futures` and press Enter. IDE inserts `futures = "[cursor]"` and opens version list.
- Press Enter again to select the first suggestion, which was usually the last stable release.

Unfortunately, this no longer works because `{}` is now the default suggestion. Choosing this suggestion generates `futures = "{[cursor]}"`, which doesn't make sense. The usefullness of `{}` in the list is questionable, as it's pretty easy to type by hand.

If I invoke autocomplete on `futures = [cursor]`, it also suggests `""` as the second best option, which is pretty useless and also gets in the way of selecting a version.

I would love to see my workflow (double press Enter to select the latest version) to work again.

Another issue is that new alpha releases appear at the top of the version list, and selecting the last stable release requires skipping the alphas. For example, For an example, for `heron` crate, he plugin currently suggests `4.0.0-alpha.2` and `4.0.0-alpha.1` first, and stable `3.1.0` is the third option. I'd argue that adding a stable version is far more common and should be prioritized in auto completion.

### PR DESCRIPTION
**Pull request by Undin**
TOML plugin has a feature to provide completion/documentation based on the corresponding JSON scheme. Previously, it didn't affect any completion because there weren't such schemes. But now there is https://json.schemastore.org/cargo.json and the feature started to affect us. As a result, some unexpected completion variants appear in the suggestion list

These changes provide our own scheme for Cargo.toml to use it instead of remote https://json.schemastore.org/cargo.json. It's empty for now that leads to no completion variants based on JSON scheme completion (including unexpected ones). It's supposed to be replaced with an actual scheme when completion is fixed

Fixes #9116

changelog: Don't suggest unexpected/duplicate completion variants in Cargo.toml

### CODE REVIEW

**Comment by Undin** [comment]
СС @avrong

**Comment by avrong** [comment]
Thanks. I'll look into this problem and schemas soon

**Comment by Undin** [comment]
@avrong I suppose the main problem is in suggesting `""` and `{}` but I haven't checked it

**Review by vlad20012 — APPROVED** [review]

**Review by ozkriff — APPROVED** [review]
looks like a fine hack to me

**Comment by Undin** [comment]
bors r=ozkriff

**Pull request merged**
