### PR TITLE
Simplify module index

### PR DESCRIPTION
**Pull request by matklad**
This depends (somewhat) on #276. 

I hope this correctly simplifies logic for resolving a `super` module (at least, no tests are broken :) ). Previously the index mapped pairs of `(module, relative file path in module)` to `rust::colon::path::to::item`. This was quite complex, didn't handle libraries well (`super::bar` in library was not resolving. The culprit was "relative" path in index. I haven't added a test for this because of the awkwardness of required setup) and was not extendable to modules without well defined `::` path:
```
fn main() {
   {
    #[path="./foo.rs"]   
    mod foo;  // the path for this would be like `::main::anonymous_block::foo`
   }
}
```

The approach proposed here is to store a mapping of `child virtual file url` -> `parent virtual file url`. It should be OK to store urls in the index, right? This does handle external crates. This *does not* handle nested non inline module like in the above example. The plan is to (in the future) switch to Stub Based index, and store a mapping `child virtual file url` -> `mod_decl item`.

As a side bonus, we no longer do [full walk from the crate root](https://github.com/intellij-rust/intellij-rust/compare/simplify-module-index?expand=1#diff-9138a61b1445e7ac9e2fe3b355c741f4L49) to resolve a `super`, and instead get to the relevant file in one step.

@alexeykudinkin please review.

### CODE REVIEW

**Comment by alexeykudinkin** [comment]
That's quite a change! Will take a more closer look tommorrow.

**Comment by alexeykudinkin** [comment]
Storing virtual file URLs isn't a supposed way of functioning of that kind of cache: it's primary role is to abstract `mod` vs. `mod` 'embedding' dependencies, which has nothing to do in particular with the notion of the file.

**Comment by matklad** [comment]
>which has nothing to do in particular with the notion of the file.

I think this is a bit exaggerated. Current implementation also stores file urls. `path` in [`RustModulePath`](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/resolve/indexes/RustModulePath.kt#L22) is a relative path to file.

**Comment by matklad** [comment]
The middle ground would be to use full url of virtual file instead of `RustModulePath`, but leave `RustQualifiedName` in place. Although at least currently we can live just fine without `RutsQualifiedName`. Are there any potential future usages for it?

**Comment by matklad** [comment]
With stdlib resolve it became relatively easy to write a test for

>`super::bar` in library was not resolving

Here is an example of this:  https://github.com/intellij-rust/intellij-rust/blob/module-index-test/src/test/resources/org/rust/lang/core/resolve/fixtures/stdlib/collections/main.rs (this is a branch with this patch applied, so the test passes)

**Comment by matklad** [comment]
>As a side bonus, we no longer do full walk from the crate root to resolve a super, and instead get to the relevant file in one step.

An interesting observation: [`super`](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/psi/util/RustModExtensions.kt#L53) is currently linear in depth, so [`canonicalName`](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/psi/util/RustModExtensions.kt#L30) and [`getCrateModuleFor`](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/resolve/util/RustResolveUtil.kt#L32) are `O(N^2)`. Luckily the depth of module tree is essentially constant.

**Comment by matklad** [comment]
@alexeykudinkin I've [found](https://github.com/intellij-rust/intellij-rust/pull/277/commits/1d5c3a68b38c7b024c431fecb9b10ba3d9e21be3) that `MacroPathManager` which magically turns absolute paths into relative ones, automagically selecting project dir or home dir as a base for an url. 

So, the strings stored in the index look like this now:

```
Urls is file://$PROJECT_DIR$/syntax/src/types.rs
Urls is file://$USER_HOME$/.cargo/registry/src/github.com-88ac128001ac3a9a/lalrpop-0.11.0/src/lr1/build/test.rs
```

**Comment by alexeykudinkin** [comment]
I've finally managed to get to this P/R.

First of all, let's preserve `qualified-name` abstraction: it's rather powerful and would definitely come to a  scene later on, to reference abstract _named_ entities.

Instead of introducing `VirtualFileUrl` let's just revisit `RustModulePath`.

Will try to do it myself, later today.

**Comment by matklad** [comment]
Ok, lets close this then!

>Will try to do it myself, later today.

Thanks! There is (almost) a test for this ready in the master branch. Change the caret in [this file](https://github.com/intellij-rust/intellij-rust/blob/master/src/test/resources/org/rust/lang/core/resolve/fixtures/stdlib/collections/main.rs#L1) to `std::collections::<caret>Bound;`. The tests should pass if files from SDK are handled correctly.

**Comment by matklad** [comment]
FYI: we handle [path attributes](https://github.com/intellij-rust/intellij-rust/blob/084d59ab2930d140bda13f4bd4dcb110561bfde7/src/test/resources/org/rust/lang/core/resolve/fixtures/mod_decl_path/main.rs) after https://github.com/intellij-rust/intellij-rust/commit/084d59ab2930d140bda13f4bd4dcb110561bfde7

This shouldn't affect the logic in Module indexer in any way.

**Comment by matklad** [comment]
@alexeykudinkin I think we should use [FileIncludeIndex](https://upsource.jetbrains.com/idea-ce/file/idea-ce-192d3c9832845bb138f4e772bd3095aa144adce4/platform/lang-impl/src/com/intellij/psi/impl/include/FileIncludeIndex.java?nav=0:0:focused) here. Kudos to @zolotov for the advice.

**Pull request closed without merging**
