### PR TITLE
CI: automatically update nightly rustc version from CI

### PR DESCRIPTION
**Pull request by Undin**
Currently, nightly rustc version is updated manually and not regularly, which leads to an outdated version of nightly compiler.
These changes introduce new GitHub workflow to update this version automatically from CI.
The schedule is set up to invoke this workflow each Monday for now

### CODE REVIEW

**Review by lancelote — APPROVED** [review]

**Comment by Kobzol** [comment]
A slightly relevant idea: maybe the gradle tasks that update compiler/clippy lints and features could also be run periodically in CI, so that they are kept up to date?

**Comment by Undin** [comment]
@Kobzol
Yep, it's a good idea. My initial goal was to make all these updates in single PR but I've decided to split them into separate PRs
That's why the corresponding workflow is called `auto updates` 😄

**Comment by mili-l** [comment]
Workflow is failed in case with space before versions name `rust-version: [ 1.54.0,  nightly-2001-08-17]`, but PR is created

**Pull request merged**
