### PR TITLE
Do not add directory as source/excluded entries if it doesn't exist

### PR DESCRIPTION
**Pull request by Undin**

### CODE REVIEW

**Comment by Undin** [comment]
СС @SergeevPavel

**Comment by SergeevPavel** [comment]
Do it will be added if I will create this folders later?

**Comment by Undin** [comment]
They will be added after next cargo refresh.
You can do in manually via the corresponding action in `Cargo` tool window or if `Watch Cargo.toml` option (I know it's not the best name) in `Preferences | Languages & Frameworks | Rust | Cargo` is enabled (it's enabled by default), the plugin invokes refresh automatically after you create any rust file in the corresponding dir

**Comment by lancelote** [comment]
Did it cause any trouble? Btw are source directories (e.g. `tests`) expected to be removed from `iml` file once deleted?

**Comment by Undin** [comment]
> Did it cause any trouble?

Not for generals users. But IDEA project has a test that checks all content roots exists. And since the project has several Rust modules, it fails this test

> Btw are source directories (e.g. tests) expected to be removed from iml file once deleted?

It would be great but it's not implemented yet and I wasn't going to implement it in this PR. But I will do it eventually

**Pull request merged**
