### PR TITLE
RUN: Show cargo output in Test Tool window

### PR DESCRIPTION
**Pull request by mchernyavsky**
Relates to https://github.com/intellij-rust/intellij-rust/issues/5676.
Relates to https://github.com/intellij-rust/intellij-rust/issues/4583.
Relates to https://github.com/intellij-rust/intellij-rust/pull/5549#issuecomment-651993198.

### CODE REVIEW

**Comment by Undin** [comment]
@mchernyavsky Can we provide some test(s) for it?
Or at least example how to check this change

**Comment by mchernyavsky** [comment]
Now the plugin prints all non-JSON messages to the root node:

image

image

Before this PR, only "Hello, World!" was printed.

This information may be useful if an error occurred when starting the tests.
For example, you can pass `--unknown` option to test binaries:

image

image

**Comment by mchernyavsky** [comment]
@Undin Done.

> error message, warning (for example, you can declare an unused variable in test)

But unused variable it's a compile-time warning

**Comment by Undin** [comment]
> But unused variable it's a compile-time warning

Yep, but now it's shown in test tool window as well

**Comment by Undin** [comment]
New test fails

**Comment by mchernyavsky** [comment]
@Undin Fixed.

**Pull request merged**
