### PR TITLE
(ANNOT): Annotate duplications at file level

### PR DESCRIPTION
**Pull request by alygin**
@matklad, your [32b916f](https://github.com/intellij-rust/intellij-rust/commit/32b916f637fb40114423bb1422c57a5c0da1a00d) commit has also fixed [the problem](https://github.com/intellij-rust/intellij-rust/pull/901#issuecomment-271079881) with duplication higlights at the file level. So, it's now much more useful.

### CODE REVIEW

**Comment by matklad** [comment]
Hm, are you sure? I still don't get file-level highlighting consistently: 

d

**Comment by alygin** [comment]
Hm, it works correctly and very reliably for me:

screen shot 2017-01-15 at 13 44 38

Could it be that something didn't recompile when you started it?

**Comment by matklad** [comment]
I've rechecked and it's definitely  still flickers for me, especially when I add/remove the trailing whitespace in the file.

**Comment by alygin** [comment]
I think you're right, it's not fixed. I don't know what it depends on, but the highlighting works fine in one files and doesn't work in others. I've noticed that the more code I have in a file, the better it works. Sounds weird, but that's how it is :(

I can't explain that, so I'm closing the PR and will carry the investigation further.

**Pull request closed without merging**
