### PR TITLE
TYPE: don't move inner attributes in 'optimize import'

### LINKED ISSUE #2248: Formatter changes order of items and breaks code
```rust
#![allow(non_snake_case)]

extern crate gtk;

use gtk::prelude::*;
use gtk::{ButtonsType, DialogFlags, MessageType, MessageDialog, Window};

fn main() {
    if gtk::init().is_err() {
        println!("Failed to initialize GTK.");
        return;
    }

    MessageDialog::new(None::<&Window>,
                       DialogFlags::empty(),
                       MessageType::Info,
                       ButtonsType::Ok,
                       "Hello World").run();
}
```

gets formatted to

```rust
// Order was changed
use gtk::{ButtonsType, DialogFlags, MessageDialog, MessageType, Window};
use gtk::prelude::*;

// Space before ! was added, which breaks code
# ![allow(non_snake_case)]

extern crate gtk;

fn main() {
    if gtk::init().is_err() {
        println!("Failed to initialize GTK.");
        return;
    }

    MessageDialog::new(None::<&Window>,
                       DialogFlags::empty(),
                       MessageType::Info,
                       ButtonsType::Ok,
                       "Hello World").run();
}
```

version 0.2.0-2275-nightly

### PR DESCRIPTION
**Pull request by Undin**
Fixes #2248

### CODE REVIEW

**Comment by Undin** [comment]
@farodin91 I've fixed this bug to release new stable version without it

**Comment by Undin** [comment]
@mkaput I don't completely sure why ignoring inner attributes in optimize import while reformatting inserts additional space in inner attribute item but looks like these changes fix it too

**Comment by mkaput** [comment]
Thx!

**Pull request merged**
