### PR TITLE
Add `updateCargoOptions` task to update cargo options automatically

### PR DESCRIPTION
**Pull request by mchernyavsky**
Closes https://github.com/intellij-rust/intellij-rust/issues/6058.
Fixes https://github.com/intellij-rust/intellij-rust/issues/6034.
Fixes https://github.com/intellij-rust/intellij-rust/issues/6096.

Closes https://github.com/intellij-rust/intellij-rust/pull/6055.

### CODE REVIEW

**Comment by Kobzol** [comment]
Btw, it's not strictly relevant to this PR, but a similar task for downloading `rustc` features (`updateCompilerFeatures`) seems to be broken, because the URLs are no longer invalid.

**Comment by Undin** [comment]
@Kobzol thanks!
It was broken by recent changes in rustc project structure
Will be fixed in #6077

**Review by Undin — COMMENTED** [review]
As we discussed in person, let's consider retrieving info from `cargo` itself instead of site. It looks like a more stable solution. Also, the corresponding parsing can be potentially used to generate the same info dynamically in the plugin itlsef

**Review by Undin — APPROVED** [review]
Awesome!

Possible future improvements: 
- currently, we understand that some option is already written and don't suggest it. For example,  for `cargo check --jobs 3` we don't suggest `--jobs` option. But if we use short variant of this option like `-j`, our completion doesn't understand it and suggests `--jobs`. Looks like we can retrieve such info as well
- fetch options of `cargo` itself

**Comment by Undin** [comment]
Note, turned out that parsing of `cargo` output is quite hard for now so we decided to use info from `https://doc.rust-lang.org/cargo/commands` page

**Review by mchernyavsky — COMMENTED** [review]
bors r+

**Pull request merged**
