### PR TITLE
Support 2019.2 EAPs

### PR DESCRIPTION
**Pull request by Undin**

### CODE REVIEW

**Comment by Undin** [comment]
@vlad20012 Could you please check that everything ok with new macro expansion events with 2019.2?

**Comment by ice1000** [comment]
How long does it take to have our first 2019.2-compatible nightly build?

**Comment by Undin** [comment]
@ice1000 Nightly builds are published about 3:00 a.m. UTC+0 automatically if there is any change from previous nightly build

**Comment by ice1000** [comment]
Ok, thanks for the information!

**Pull request merged**
