### PR TITLE
CARGO: Fix documentation link for renamed dependency

### LINKED ISSUE #3361: Support renamed dependency in Config.toml
## Environment

* **Intellij-Rust plugin version:** `v0.2.91.2115-191`
* **Toml Plugin version:** `v0.2.0.21`
* **Rust toolchain version:** `stable-x86_64-unknown-linux-gnu  rustc 1.32.0 (9fda7c223 2019-01-16)`
* **IDE name and version:** `CLion 2019.1 EAP (#CL-191.4738.15)`
* **Operating system:**: `Fedora 29 (4.20.6-200.fc29.x86_64)`

## Problem description

rust-lang/cargo#6311 `rename-dependency` of cargo has been [landed](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml), so it would be helpful if toml plugin supports this feature.

For example,  if `cargo.toml` is:
```
[dependencies]
config_rs = { package = "config", version = "0.9" }
```
, then document link should link to https://docs.rs/config/0.9/config, not https://docs.rs/config_rs/0.9/config_rs .

### PR DESCRIPTION
**Pull request by bc-lee**
Fixes #3361

### CODE REVIEW

**Comment by Undin** [comment]
@bc-lee I see you've already signed our CLA. Thanks!
Could you add your Github username to `CONTRIBUTORS.txt` file?

**Comment by bc-lee** [comment]
@Undin All comments have been addressed.

**Comment by Undin** [comment]
Looks great, thanks!
And welcome to intellij-rust contributors!
bors r+

**Comment by Undin** [comment]
bors retry

**Pull request merged**
