### PR TITLE
ACT: Add impl for QualifiedNameProvider

### PR DESCRIPTION
**Pull request by dimonchik0036**
Impl #2544

### CODE REVIEW

**Comment by Dimonchik0036** [comment]
Now if we have this train
```
trait Show {
    fn show(&self) -> String;
}
```
it  look like as `package::show`

**Comment by Dimonchik0036** [comment]
```rust
mod world {
    trait House {
        fn say_hello(&self) -> String;
    }
}
```
Look like as `package::world::House#say_hello`

**Comment by Dimonchik0036** [comment]
@Undin what do you think?

**Comment by mehcode** [comment]
Why `#` ? Rust uses `::` everywhere normally.

**Comment by Dimonchik0036** [comment]
@mehcode `#` is used to show that the function belongs to the trait. Perhaps it really is not necessary.

**Comment by mehcode** [comment]
Universal function call syntax in rust still uses `::` for functions in traits. 

E.g.. 

```rust
package::world::House::say_hello(foo)
```

Given the issue (copying a qualified reference for intended usage in code) I would assume the intention is to make UFCS easier to write if necessary.

**Comment by Dimonchik0036** [comment]
@mehcode You are right, I will correct it.

**Comment by Kobzol** [comment]
@dimonchik0036 Are you planning to finish this PR? :) Otherwise I can try to finish it.

**Comment by dimonchik0036** [comment]
@Kobzol Too much time has passed that I even forgot. 😄 
You can finish this PR.

**Pull request closed without merging**
