### PR TITLE
PERF: don't calculate CFG, Liveness and borrowck in cfg-disabled code

### PR DESCRIPTION
**Pull request by vlad20012**

### CODE REVIEW

**Comment by stepancheg** [comment]
Probably after this commit, functions are no longer clickable in cfg-disabled code. Worked a few weeks ago, does not work now.

image

This is somewhat inconvenient when working e.g. on linux-windows code.

Would be helpful if intellij-rust could do the opposite: properly analyse/highlight cfg-disabled code.

CLion Build #CL-223.8214.51, built on December 20, 2022
Intellij-rust 0.4.185.5086-223

**Comment by vlad20012** [comment]
@stepancheg None of CFG, Liveness or borrowck are related to go-to-declaration or type inference inside cfg-disabled code, so your issue is obviously unrelated to this PR

**Comment by ortem** [comment]
@stepancheg I am not sure if the navigation was supposed to work inside `cfg`-disabled code in the previous releases. But to get it working properly in your scenario, you can change the build target in the Cargo config, as described in the corresponding [issue](https://github.com/intellij-rust/intellij-rust/issues/5188). Please let us know if this helps.

**Comment by stepancheg** [comment]
Switching back and forth is not as convenient as having them all available at the same time. But if it works as it is meant to be, nevermind, this it not a big issue.

Thank you for the plugin!

**Pull request merged**
