### PR TITLE
Fix #6183

### LINKED ISSUE #6183: `Make self mutable` changes `self` to `&mut self` instead of `mut self`
## Environment

* **IntelliJ Rust plugin version:** 0.3.131.3366-202
* **Rust toolchain version:** 1.48.0-nightly (fb1dc34a8 2020-09-21) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2020.2.3 (CL-202.7319.72)
* **Operating system:** Linux 5.8.12-arch1-1

## Problem description
In the following code, Rust plugin correctly highlights error `Cannot assign to field of immutable binding [E0594]` and suggests to ``Make `self` mutable``.
```rust
struct TestStruct{
    a: i32
}

impl TestStruct{
    pub fn test(self){
        self.a = 4;
    }
}
```
But instead of changing `self` to mutable (`mut self`), it changes `self` to a mutable reference (`&mut self`)

screenshot

### Expected
```rust
struct TestStruct{
    a: i32
}

impl TestStruct{
    pub fn test(mut self){
        self.a = 4;
    }
}
```

### Actual
```rust
struct TestStruct{
    a: i32
}

impl TestStruct{
    pub fn test(&mut self){
        self.a = 4;
    }
}

```
## Steps to reproduce
1. Copy the code to CLion with Rust plugin
1. Click on  the highlighted error and click on ``Make `self` mutable``

### PR DESCRIPTION
**Pull request by ondralukes**
Fixes #6183 
``Make `self` mutable`` suggestion in the following code changes `self` to `&mut self` instead of `mut self`
```rust
struct TestStruct{
    a: i32
}

impl TestStruct{
    pub fn test(self){
        self.a = 4;
    }
}
```

### CODE REVIEW

**Comment by Kobzol** [comment]
Welcome and thank you for the PR :smiley: Could you also add a corresponding test to `AddMutableFixTest`? Thanks!

**Comment by ondralukes** [comment]
Hi, thanks for your feedback. I've added 2 tests: `test fix E0594 assign to field of immutable binding` and `test fix E0596 borrow self as mutable`

**Review by vlad20012 — APPROVED** [review]
Hello! Thanks for the PR!
I see you're a first-time contributor. Could you, please, sign our `Contributor License Agreement` as mentioned in [CONTRIBUTING.md](https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md#cla)?

**Comment by ondralukes** [comment]
Hi, I've already signed the CLA.

**Comment by vlad20012** [comment]
Oh, OK, thanks!
bors r+

**Pull request merged**
