### PR TITLE
Enable build script evaluation by default

### LINKED ISSUE #4631: Support cfg features generated by build scripts
## Environment

* **IntelliJ Rust plugin version:** 0.2.110.5742-193-dev
* **Rust toolchain version:** 1.39 stable
* **IDE name and version:** IntelliJ IDEA 2019.3 beta 2
* **Operating system:** Windows 10 x64

## Problem description
Ctrl-clicking function in specific circumstance takes me to wrong function. Experimental macro expansion engine is enabled.

## Steps to reproduce

Cargo.toml:

```toml
[package]
name = "bug-repro"
version = "0.1.0"
authors = ["Alyosha Vasilieva <1284317+AlyoshaVasilieva@users.noreply.github.com>"]
edition = "2018"

[dependencies]
indexmap = "=1.3.0"
digest = "=0.8.1"
```

main.rs:

```rust
use indexmap::map::IndexMap;

fn main() {
    let mut map = IndexMap::new();
    map.insert("key", "value");
}
```

`IndexMap::new` is highlighted as error with "Unresolved reference: \`new`".

Ctrl-clicking IndexMap, despite being highlighted red, correctly takes me to its declaration.

Ctrl-clicking `new` incorrectly takes me to the `new` function inside `impl<D: Input + FixedOutput + Reset + Clone + Default> Digest for D`, part of the `digest` crate.

Compilation works and gives no warnings or errors.

### LINKED ISSUE #6135: Output from bindgen doesn't get included in build tree
## Environment

* **IntelliJ Rust plugin version:** 0.3.130.3337-202
* **Rust toolchain version:** 1.48.0-nightly (bbc677480 2020-09-18) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.2.3 (CL-202.7319.72)
* **Operating system:** macOS 10.15.6

## Problem description

When using `bindgen`or similar crate, that generates Rust code at build time for inclusion in the project, that generated code doesn't become part of the build tree. That means I can't jump to functions declared there and also have to manually search for the generated `.rs` file in the `target` folder.

As the output is included in the overall project via `include!(concat!(env!("OUT_DIR"), "/generated-bindings-sys.rs"));` it should be available for analysis and reference inside the IDE.

### LINKED ISSUE #6539: Autocomplete issue
## Environment

* **IntelliJ Rust plugin version: 0.3.137.3543-203**
* **Rust toolchain version: 1.48.0 **
* **IDE name and version: Clion 2020.3 **
* **Operating system: 5.9.11-3-MANJARO Linux**

## Problem description
Having a package dependency gdnative = "0.9.1"
I dont have autocomplete for some types like gdnative::api::{Area, MeshInstance, CollisionShape};
But if I compile the code it works normally.
One friend told me that I need to enable "Load code from OUT_DIR"

## Steps to reproduce
Create a new project, add gdnative as a dependency and try to autocomplete  some type that is inside  gdnative::api::...

### LINKED ISSUE #7145: Spurious unresolved reference errors
## Environment

* **IntelliJ Rust plugin version:** 0.3.145.3797-211
* **Rust toolchain version:** 1.51.0 (43b129a20 2021-03-16)
* **IDE name and version:** IntelliJ IDEA Community 2021.1 (Flatpak)
* **Operating system:** Debian bullseye (5.10.0-6-amd64)

## Problem description
Spurious unresolved reference errors about len() and is_empty() methods on an indexmap::set::IndexSet reference are shown in the editor when the regex crate is included in the project.

They seem to be confused with methods of the same names in regex::internal::Input. No errors are shown when actually nonexistent methods are referenced.

## Steps to reproduce
1. Clone and open https://github.com/hb16/intellij-rust-bug-demo-1.git
2. Open src/main.rs

### LINKED ISSUE #8007: Completion does not work with IndexMap (indexmap crate)
## Environment

* **IntelliJ Rust plugin version:** 0.4.157.4174-212
* **Rust toolchain version:** 1.55.0 (c8dfcfe04 2021-09-06) x86_64-pc-windows-msvc
* **IDE name and version:** CLion 2021.2.3 (CL-212.5457.51)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description

Rust Plugin seems to unable to decide which of implementations to use (there are no_std and regular versions), and so autocompletion does not work.

## Steps to reproduce

1. Add indexmap crate

```rust
fn main() {
  indexmap::IndexMap:: // completion does not work here
}
```

### LINKED ISSUE #9093: Types autocomplete and go-to-defenition are not working with k8s-openapi
## Environment

* **IntelliJ Rust plugin version:** 0.4.164.4409-212
* **Rust toolchain version:** 1.57.0 (f1edd0429 2021-11-29) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2021.2.4 Ultimate Edition (IU-212.5712.43)
* **Operating system:** macOS 12.2.1
* **Macro expansion engine:** new
* **Name resolution engine:** new

## Problem description
I installed `k8s-openapi` dependency and can't use it's types and go-to-definition feature, for example - `k8s_openapi::api::core::v1::Pod`
When I try to go-to-defenition to `Pod`, I get message `Cannot find declaration to go to`, but I can go-to `::api::`, so it means that it finds `api/mod.rs`, but not `core`, for some reason.
When I try to use variable, that don't print type hints and there is no autocomplete.

p.s. build process works without errors

## Steps to reproduce
Install `k8s-openapi = { version = "0.15.0", features = ["v1_24"] }`
Import `k8s_openapi::api::core::v1::Pod` and try to use autocomplete/go-to-defenition

```rust
use k8s_openapi::api::core::v1::Pod;
use kube::{
    api::{Api, ListParams, PostParams, ResourceExt},
    Client,
};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = Client::try_default().await?;
    let pods: Api<Pod> = Api::default_namespaced(client);
}
```

### LINKED ISSUE #9402: Stabilise org.rust.cargo.evaluate.build.scripts
## Environment

* **IntelliJ Rust plugin version:** 0.4.178.4873-222
* **Rust toolchain version:** 1.63
* **IDE name and version:** Clion 2022.2.3
* **Operating system:** Linux

## Problem description

First of all thank you so much for this plugin, it is awesome :+1:

My problem is more of a question, I find myself recommending people enable the experimental feature `org.rust.cargo.evaluate.build.scripts` in order for the plugin to pick up code generated to and then `include!`d from `OUT_DIR`. 

This is a fairly common pattern used by [prost](https://docs.rs/prost-build/latest/prost_build/) and [cranelift](https://docs.rs/cranelift-codegen/latest/cranelift_codegen/) to name a few.

My questions are therefore:

* What is experimental about this feature, is it dangerous, unstable, or just not fully polished yet
* Are there downsides to enabling this feature
* Is there a path to enabling this feature by default, as I think with the recent proc macro work (mega kudos btw) this is the last major pain point I see users run into frequently

## Steps to reproduce

A test example that appears to only work with this feature enabled can be found - https://github.com/apache/arrow-datafusion/pull/3580#issuecomment-1256432671

### LINKED ISSUE #9535: Incorrect Unresolved reference: `contains` when using `IndexSet` and `itertools`
## Environment

* **IntelliJ Rust plugin version: 0.4.180.4932-222**
* **Rust toolchain version: 1.64.0**
* **IDE name and version: CLion 2022.2.3 Build #CL-222.4167.35, built on September 15, 2022**
* **Operating system:**

## Problem description
`IndexSet` provides a public function called `contains()` but the IDE marks it as an invalid reference. The code compiles and works fine.

This has been narrowed down to some kind of conflict with the `itertools` crate. When it is specified in the `Cargo.toml` file as a dependency the error appears. When it is removed, the error goes away. Somehow the Rust plugin is getting confused, even if `itertools` is not even used in that specific file. 

image

## Steps to reproduce

1. Create a new Rust project named `test-indexset`
2. Replace `Cargo.toml` with the following:

```toml
[package]
name = "test-indexset"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "1.9.1"
#comment out the next line and the error goes away
itertools = "0.10.3"
```

3. Replace `main.rs` with the following code:

```rust
use indexmap::IndexSet;

fn is_inside(set: &IndexSet<String>, needle: &str) -> bool {
    return set.contains(needle)
}

fn main() {
    let mut set = IndexSet::new();
    set.insert("hello".to_string());
    set.insert("goodbye".to_string());

    let inside = is_inside(&set, "hello");
    println!("{}", inside);
}
```

Even though `itertools` is not used in the file, it will show the error in the IDE. 
If you compile and run the program it will work successfully.

If you comment out the `itertools` dependency in `Cargo.toml` the error will go away.

### PR DESCRIPTION
**Pull request by Undin**
Fixes #4631
Fixes #6135
Fixes #7145
FIxes #8007
Fixes #6539
Fixes #9093
Fixes #9535

Closes #9402

changelog: Enable [build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html) evaluation by default. Now the plugin builds and executes all build scripts in the project (including build scripts in external dependencies) during project model loading to create source code generated during compilation and collect information about generated environment variables and `cfg` options. A typical use case is to generate some code by a build script and include it via `include!(concat!(env!("OUT_DIR"), "/path_to_generated_file.rs"))`. Now the plugin understands where generated code is located and includes them into its own analysis.
Under the hood, build script evaluation uses `cargo check` call modified in a way to compile and execute only host code (i.e. only buil scripts and procedural macros as well as their dependencies). Besides execution of build scripts code, it also allows the plugin to compile all procedural macro libraries which is required for procedural macro expansion. Note, procedural macro expansion is still disabled by default. To turn it on, enable `org.rust.macros.proc` [experimental](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) feature

### CODE REVIEW

**Review by vlad20012 — APPROVED** [review]

**Comment by vlad20012** [comment]
Btw it would be nice to fix #9399 :thinking:

**Comment by Undin** [comment]
bors r=vlad20012

**Comment by vlad20012** [comment]
It's not nearly as epic as #5716
image

**Comment by Undin** [comment]
Because it's still a preparation for procedural macro expansion

**Pull request merged**
