### PR TITLE
INSP: configure project to run inspections from command line

### PR DESCRIPTION
**Pull request by Undin**
Provide implementation of `CommandLineInspectionProjectConfigurator` EP to properly configure project model for cargo-based projects for running inspection from [command line](https://www.jetbrains.com/help/idea/command-line-code-inspector.html) or via [Qodana](https://www.jetbrains.com/qodana/)

changelog: properly configure cargo-based projects for running inspection from [command line](https://www.jetbrains.com/help/idea/command-line-code-inspector.html) or via [Qodana](https://www.jetbrains.com/qodana/)

### CODE REVIEW

**Comment by Undin** [comment]
СС @mili-l

**Comment by mchernyavsky** [comment]
@Undin 

When I run this command:

```
docker run --rm -it \
-v /Users/Mikhail.Chernyavsky/CLionProjects/sandbox/:/data/project/ \
-v /Users/Mikhail.Chernyavsky/CLionProjects/sandbox/results:/data/results \
-v /Users/Mikhail.Chernyavsky/CLionProjects/intellij-rust/plugin/build/distributions/intellij-rust:/opt/idea/plugins/intellij-rust \
-p 8080:8080 \
repo.labs.intellij.net/static-analyser/qodana-rust
```

on this code:

``` rust
fn main() {
    let x: i32 = "42";
}
```

I get this result:

```
By using this Docker image, you agree to
- JetBrains Privacy Policy (https://jb.gg/jetbrains-privacy-policy)
- Qodana Community Linters Agreement (https://jb.gg/qodana-community-linters)
                                        
          _              _       
         /\ \           /\ \        Qodana for Rust 2022.2
        /  \ \         /  \ \       Documentation
       / /\ \ \       / /\ \ \      https://jb.gg/qodana-docs
      / / /\ \ \     / / /\ \ \     Contact us at
     / / /  \ \_\   / / /  \ \_\    qodana-support@jetbrains.com
    / / / _ / / /  / / /   / / /    Or via our issue tracker
   / / / /\ \/ /  / / /   / / /     https://jb.gg/qodana-issue
  / / /__\ \ \/  / / /___/ / /      Or share your feedback at our forum
 / / /____\ \ \ / / /____\/ /       https://jb.gg/qodana-forum
 \/________\_\/ \/_________/     
                                                   
                                        
Starting up Qodana for Rust 2022.2 (build QDRST-223.2151.118) ...done.
Preparing for the Project opening stage ...
(Project opening) done.                                                         
The Project opening stage completed in 4s 610ms
Initializing project...Inspecting with the 'qodana.starter' profile
2022-08-03 18:53:14,955 [   6360]   WARN - #o.j.p.s.s.GitReportContributor - Unable to find the remote url, please set the environment variable QODANA_REMOTE_URL
 0%
2022-08-03 18:53:16,524 [   7929] SEVERE - #o.j.p.s.w.GitCommitsSummaryLogger - ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
com.intellij.openapi.vcs.VcsException: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
        at git4idea.commands.GitCommandResult.throwOnError(GitCommandResult.java:156)
        at org.jetbrains.plugins.staticAnalysis.workflow.GitCommitsSummaryLogger.commitsSummarySince(GitCommitsSummaryLogger.kt:58)
        at org.jetbrains.plugins.staticAnalysis.workflow.GitCommitsSummaryLogger.beforeLaunch(GitCommitsSummaryLogger.kt:32)
        at org.jetbrains.plugins.staticAnalysis.workflow.QodanaWorkflowExtension.callBeforeLaunch(QodanaWorkflowExtension.java:16)
        at org.jetbrains.plugins.staticAnalysis.inspections.runner.QodanaRunner.runScript(QodanaRunner.kt:358)
        at org.jetbrains.plugins.staticAnalysis.inspections.runner.QodanaRunner.run(QodanaRunner.kt:82)
        at org.jetbrains.plugins.staticAnalysis.inspections.runner.QodanaInspectionApplication.run(QodanaInspectionApplication.kt:121)
        at com.intellij.codeInspection.InspectionApplicationBase.execute(InspectionApplicationBase.java:152)
        at com.intellij.codeInspection.InspectionApplicationBase.startup(InspectionApplicationBase.java:120)
        at com.intellij.codeInspection.InspectionMain.main(InspectionMain.java:115)
        at com.intellij.idea.ApplicationLoader$doInitApplication$2$7.invokeSuspend$lambda-0(ApplicationLoader.kt:162)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2022-08-03 18:53:16,528 [   7933] SEVERE - #o.j.p.s.w.GitCommitsSummaryLogger - Qodana for Rust 2022.2  Build #QDRST-223.2151.118
2022-08-03 18:53:16,532 [   7937] SEVERE - #o.j.p.s.w.GitCommitsSummaryLogger - JDK: 11.0.12; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-08-03 18:53:16,534 [   7939] SEVERE - #o.j.p.s.w.GitCommitsSummaryLogger - OS: Linux
 0%
Preparing for the Project configuration stage ...
(Project configuration) Cargo project model loading finished: SUCCESS           
The Project configuration stage completed in 42s 348ms
Preparing for the Project analysis stage ...
(Project analysis) Analyzing code 31% [main.rs]                                 
The Project analysis stage completed in 263ms

Qodana - Detailed summary
Analysis results: 0 problems detected
2022/08/03 18:54:02 IDEA exit code: 0
2022/08/03 18:54:02 Sync IDEA cache from: /data/project/.idea to: /data/cache/.idea
```

**Comment by Undin** [comment]
@mchernyavsky it seems it's because of `qodana.starter` profile
try this one:
```
docker run --rm -it \
-v /Users/Mikhail.Chernyavsky/CLionProjects/sandbox/:/data/project/ \
-v /Users/Mikhail.Chernyavsky/CLionProjects/sandbox/results:/data/results \
-v /Users/Mikhail.Chernyavsky/CLionProjects/intellij-rust/plugin/build/distributions/intellij-rust:/opt/idea/plugins/intellij-rust \
-p 8080:8080 \
repo.labs.intellij.net/static-analyser/qodana-rust \
-profileName Default
```

**Review by mchernyavsky — APPROVED** [review]
LGTM

**Comment by Undin** [comment]
bors r=mchernyavsky

**Pull request merged**
