### PR TITLE
Parse rust path in short doc links

### LINKED ISSUE #6905: Refactor doc comment links when refactoring code
## Environment

* Plugin 0.3.141.3674-203

## Problem description

When refactoring code, e.g. the name of a Trait, doc links are not updated.

## Steps to reproduce

Have some code with a doc comment:

```rust
trait MyTrait {
}

/// This is a subtrait of [MyTrait].
trait OtherTrait: MyTrait {
}
```

Now Refactor -> Rename MyTrait.

Error: The `[MyTrait]` link was not updated.

### PR DESCRIPTION
**Pull request by dima74**
Continuation of #7353

Now paths in short links are parsed as `RsPath`, and thus resolve and completion works for them. Note that short links can be either a path or a label, depending on the existence of the corresponding link definition for the label

```rust
/// [bar1] - direct link
/// [bar2] - markdown label reference
///
/// [bar2]: bar3
fn foo() {}
```

This together with #9688 will fix #6905

changelog: Support short [intra-doc links](https://doc.rust-lang.org/rustdoc/write-documentation/linking-to-items-by-name.html) (in format `[link]`)

### CODE REVIEW

**Review by vlad20012 — APPROVED** [review]
LGTM

Btw does rustdoc disallows spaces between brackets and backticks like this:
```
[  `foo`  ]
```
?

**Comment by dima74** [comment]
> Btw does rustdoc disallows spaces between brackets and backticks like this:
> 
> ```
> [  `foo`  ]
> ```
> 
> ?

Spaces are allowed, fixed

**Comment by vlad20012** [comment]
> Spaces are allowed

And what about tabs, are they allowed? :D

**Comment by dima74** [comment]
> And what about tabs, are they allowed? :D

Looks like yes, fixed

**Review by vlad20012 — APPROVED** [review]
bors r+

**Pull request merged**
