### PR TITLE
(PSI) add Rust logo to all Rust icons

### LINKED ISSUE #306: Add Rust logo to all Rust icons
Take a look at his screenshot:

icons

The lower two icons are for Kotlin classes and they are easy distinguishable because of a small Kotlin logo. The upper two icons are for Rust structs, but it is not that easy to guess.

### PR DESCRIPTION
**Pull request by zjhmale**
Fix #306

### CODE REVIEW

**Comment by matklad** [comment]
This is not exactly what is needed here. We still want different icons for different Rust items:

icons


I think that adding a small R (maybe without circle?) to the lower right corner should do the trick.

**Comment by zjhmale** [comment]
just like kotlin right?  i will get these icons done.

**Comment by matklad** [comment]
Yes, like Kotlin. I think there should be a way of composing Rust icon over existing icons, and that we don't need to duplicate actual icon pictures.

**Comment by zjhmale** [comment]
kotlin maintains the icons itself, so maybe there is not possible of composing customize icon over existing icons? just almost 5 or 6 icons, not a big deal to duplicate exist icon pictures here i think.

https://github.com/JetBrains/kotlin/blob/master/idea/idea-analysis/src/org/jetbrains/kotlin/idea/KotlinIcons.java

https://github.com/JetBrains/kotlin/blob/master/idea/resources/org/jetbrains/kotlin/idea/icons/classKotlin.png

**Comment by matklad** [comment]
Hm, on the other hand, do we really need this feature? 

Kotlin surely needs it, because it is used together with Java and it is important to distinguish Java and Kotlin items. 

Rust, on the other hand, is usually used by itself, so there is no information added by Rust logo. It only would clutter the icon. 

I would like to have this feature personally, because intelij-rust is a mixed Kotlin/Rust/Java codebase, but I am a minority here :)

Sorry for a won't fix feature request :)

**Comment by zjhmale** [comment]
it's ok :)

**Pull request closed without merging**
