### PR TITLE
UI: Alphabetical sort for all files in project view

### PR DESCRIPTION
**Pull request by mchernyavsky**
Closes https://github.com/intellij-rust/intellij-rust/issues/8806.

Reverts https://github.com/intellij-rust/intellij-rust/issues/7424.

changelog: Alphabetical sort for all files in the project view

### CODE REVIEW

**Review by ozkriff — APPROVED** [review]

**Comment by vlad20012** [comment]
This sounds a bit controversial. Couldn't we add an option to sort alphabetically or sort "somehow" with `lib.rs` on top?

**Comment by vlad20012** [comment]
Ok, I think alphabetical sorting is usually expected by default, and I'm not sure how useful current sorting is. So let's merge it for now

bors r+

**Comment by neonaot** [comment]
Hi guys! 
Can you please explain the reasons for reverting https://github.com/intellij-rust/intellij-rust/issues/7424? 
Changes in the UI affect all users, and we would like to understand the motivation. 
cc @mili-l

**Comment by vlad20012** [comment]
@neonaot It should be possible to sort files alphabetically. Previously we just sorted `mod.rs` files and crate roots (`main.rs`/`lib.rs) to the top without an option that can be disabled. Also, I couldn't find any other IDE/plugin that does things like that.

I think that if we want to apply some kind of non-alphabetical sorting, we must provide a UI option to disable it. Since both me and @mchernyavsky don't know how to add that option, we concluded that it's not worth the time we would spend on investigating it, so we decided to just rollback to the default alphabetical sorting for now

**Comment by neonaot** [comment]
@vlad20012 , right now we have a problem with UX: users had `main&lib` at the top of the list for a long time and everyone got used to it. 
This PR had moved UI button `main.rs` somewhere in the middle of the list.  As a result, many users will spend some time finding needed files. 

I agree with the logic that behaving like other Ide/plugins is a good idea, but not all languages have such specific files (as `lib.rs`), and maybe we need some survey/research about what is more convenient for users in the case of Rust.  

But the main issue here is not the type of sorting, but the unexpected change in the user interface.

**Comment by vlad20012** [comment]
@neonaot so what's your advice?

**Comment by neonaot** [comment]
@vlad20012 let's revert this PR (https://github.com/intellij-rust/intellij-rust/pull/10306) for now.  And discuss it after some investigations later. 

confirmed by @mili-l

**Comment by mchernyavsky** [comment]
Hi @neonaot,

I agree with your assessment that unexpected changes in the user interface can negatively impact user experience. However, in this case, reverting the pull request seems to be the right decision.

While it's true that users have gotten used to having certain files at the top of the list, we must also consider the fact that not all users share the same preferences. In fact, some users may prefer to have the files sorted alphabetically. Therefore, it's important to provide a consistent and predictable user experience across all sorting options, rather than catering to specific preferences.

Furthermore, the fact that this feature doesn't work correctly with other sorting options, like "Sort by Type," is a significant issue. This means that users who prefer to sort files by type may not be able to locate the files they need quickly and easily. This could lead to frustration and decreased productivity.

Another important point to consider is that we couldn't find any other IDE or plugin that has a similar non-alphabetical sorting option for files. This means that users who switch between different programming languages may find this sorting behavior inconsistent and confusing.

Providing a unique sorting option that deviates from the common approach taken by other plugins could cause confusion and reduce the ease of use for those users. Therefore, until we can confirm that there is significant demand for such a feature, it's best to stick to the standard sorting options that users are accustomed to.

I hope this argument helps to further support the decision to revert the pull request.

Best,
@mchernyavsky

**Comment by U007D** [comment]
Hi, I have been looking for this feature for quite some time--my CLion (2023..2.2 + latest IntelliJ Rust plugin) and my RustRover (2023.2) are _still_ not listing files in the Project pane strictly alphabetically.

Is there something special I need to do to enable this PR in my IDE?

**Pull request merged**
