### PR TITLE
Up/Down mover: move `match arm` in closure

### LINKED ISSUE #6629: Move statement up/down does not work inside closures
## Environment

* **IntelliJ Rust plugin version:** 0.3.138.3572-203
* **Rust toolchain version:** 1.50.0-nightly (a0d664bae 2020-11-22) x86_64-apple-darwin
* **IDE name and version:** CLion 2020.3 (CL-203.5981.166)
* **Operating system:** macOS 10.16
* **Macro expansion engine:** disabled
* **Name resolution engine:** old

## Problem description
move_stmt_bug

The implementation of this action is located in `src/main/kotlin/org/rust/ide/actions/mover`

## Steps to reproduce
```Rust
fn main() {
    let xs: Vec<_> = vec![1,2,3].iter().map(|x| {
        match x {
            1 => 10,
            2 => 20, // Move statement up or down
            _ => 30
        }
    }).collect();
}
```

### PR DESCRIPTION
**Pull request by t-kameyama**
Fixes #6629

### CODE REVIEW

**Comment by ortem** [comment]
Hi @t-kameyama, that you for your PR!

Currently, it looks like your implementation breaks the expected behaviour if you try to move *the first arm down* or *the last arm up* in this case:
```Rust
fn foo() {
    match x {
        1 => 10,
        2 => {
            20;
            30;
        }
        _ => 40,
    };
}
```
and throws the following exception:
```
java.lang.IllegalStateException: Check failed.
	at org.rust.ide.formatter.processors.RsTrailingCommaFormatProcessorKt.isLastElement(RsTrailingCommaFormatProcessor.kt:95)
	at org.rust.ide.actions.mover.RsCommaListElementUpDownMover.beforeMove(RsCommaListElementUpDownMover.kt:58)
	at com.intellij.codeInsight.editorActions.moveUpDown.MoverWrapper.move(MoverWrapper.java:57)
        ...
```

**Review by ortem — CHANGES_REQUESTED** [review]
Hi @t-kameyama, that you for your PR!

Currently, it looks like your implementation breaks the expected behaviour if you try to move *the first arm down* or *the last arm up* in this case:
```Rust
fn foo() {
    match x {
        1 => 10,
        2 => {
            20;
            30;
        }
        _ => 40,
    };
}
```
and throws the following exception:
```
java.lang.IllegalStateException: Check failed.
	at org.rust.ide.formatter.processors.RsTrailingCommaFormatProcessorKt.isLastElement(RsTrailingCommaFormatProcessor.kt:95)
	at org.rust.ide.actions.mover.RsCommaListElementUpDownMover.beforeMove(RsCommaListElementUpDownMover.kt:58)
	at com.intellij.codeInsight.editorActions.moveUpDown.MoverWrapper.move(MoverWrapper.java:57)
        ...
```

**Comment by ortem** [comment]
@t-kameyama Thank you, now it seems to work fine!

Please add the tests I mentioned here https://github.com/intellij-rust/intellij-rust/pull/6655#pullrequestreview-574960443 (AFAIU your tests are a bit different) and squash the commits before merging.

**Review by ortem — APPROVED** [review]

**Comment by t-kameyama** [comment]
Added tests:
https://github.com/t-kameyama/intellij-rust/blob/5f96e7cba3ca08b5ee2135e131e1545f5b63e690/src/test/kotlin/org/rust/ide/actions/mover/RsMatchArmUpDownMoverTest.kt#L241-L287

**Review by ortem — APPROVED** [review]
Thank you @t-kameyama!
bors r+

**Pull request merged**
