### PR TITLE
[WIP] Register Module Source Roots To Create Project from IDEA

### PR DESCRIPTION
**Pull request by 06needhamt**
Work In Progress Do Not Merge !!!

### CODE REVIEW

**Comment by matklad** [comment]
Hm, we already have a thing for detecting project structure: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/idea/RustProjectStructureDetector.kt.

I wonder if we could somehow invoke `cargo new` when creating a new project, and then just reuse `RustProjectStructureDetector`.

**Comment by matklad** [comment]
Turns out that the simplest way to create content roots was inheriting from JavaModuleBuilder: https://github.com/intellij-rust/intellij-rust/commit/968e29095428a092fb723a3ac7ed0420ee4b0eda

**Comment by 06needhamt** [comment]
@matklad Everything Works Fine Now

**Comment by matklad** [comment]
Good to hear, thanks for conformation!

**Pull request closed without merging**
