### PR TITLE
(c)

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by mkaput** [comment]
I think we could configure intellij to automatically manage license comments

**Comment by matklad** [comment]
>I think we could configure intellij to automatically manage license comments

Yep, I've used the copyright plugin to actually update the copyrights. However, it is important to check them during CI, and looks like nothing can beat a little bash script here :) There are a couple of Gradle plugins for licenses there, but they all seemed kind of clunky to me :(

**Comment by mkaput** [comment]
I have nothing against bash, just it would be nice if intellij would automatically insert license comment in new files :)

**Comment by matklad** [comment]
Hm, yeah, I think I can try to figure out how to share copyright's plugin config...

**Comment by mkaput** [comment]
It's stored in `.idea/copyright` if I recall correctly

**Comment by matklad** [comment]
Yep, you are right! https://github.com/intellij-rust/intellij-rust/commit/4f40440a0033eaae0ed77418e382001011e5fa07

**Pull request merged**
