### PR TITLE
DOC: the oldest current supported IDE version is 2017.2

### PR DESCRIPTION
**Pull request by Undin**

### CODE REVIEW

**Comment by matklad** [comment]
Though, perhaps we can strip this info altogether? 

It was relevant when the plugin only appeared, and there existed IDEA version for which not a single version of plugin worked. Now, you can install plugin anywhere, but you won't received updates for older IDEs.

**Comment by Undin** [comment]
Hm, but still there are old versions of IDEA where plugin doesn't work at all.
But it is really not very useful info because plugin repository contains this info (and info about each plugin version) and it is more relevant in case of plugin installation.

**Comment by matklad** [comment]
>Hm, but still there are old versions of IDEA where plugin doesn't work at all.

That's like 14.something versions, I doubt anyone uses them :)

**Pull request merged**
