### PR TITLE
RUN: Support `Emulate terminal in output console` option for wasm-pack configurations

### PR DESCRIPTION
**Pull request by mchernyavsky**
Depends on https://github.com/intellij-rust/intellij-rust/pull/8916.

changelog:  Support `Emulate terminal in output console` option for wasm-pack configurations

### CODE REVIEW

**Comment by bravit** [comment]
Hi! Any progress with this?

**Review by ortem — CHANGES_REQUESTED** [review]
I found the following problem: when I unselect `org.rust.cargo.emulate.terminal` and then create an implicit `wasm-pack` run configuration (from `Run Anything`), I still get a configuration with selected `Emulate terminal in output console`

**Review by ortem — APPROVED** [review]
LGTM

**Review by mchernyavsky — COMMENTED** [review]
bors r=ortem

**Review by mchernyavsky — COMMENTED** [review]
bors r=ortem

**Pull request merged**
