### PR TITLE
INSP: don't apply RsStaticConstNamingInspection for extern statics

### LINKED ISSUE #6023: RsStaticConstNaming shouldn't inspect extern statics
## Problem description
I don't believe this is intentional, but there's an inspection on the naming of extern statics. You don't exactly get to decide their name (especially if it's C) while this implies that you should change it as if that wouldn't prevent the linker from making it work, I don't believe you should be the one getting the warning.

## Example
image

### PR DESCRIPTION
**Pull request by Undin**
Fixes #6023

### CODE REVIEW

**Review by Kobzol — APPROVED** [review]
LGTM

**Comment by Undin** [comment]
bors r=Kobzol

**Comment by vlad20012** [comment]
Should associated constants be checked? Looks like this PR exclude them

**Comment by Kobzol** [comment]
AFAIK this is only about statics, and these cannot be associated. Constants are checked by a different lint, because they use a different lint message.

**Comment by Undin** [comment]
> Should associated constants be checked? Looks like this PR exclude them

Yep, it only about `static`s

**Pull request merged**
