### PR TITLE
GRAM&ANN: parse `unsafe` keyword in modules and annotate it as error

### PR DESCRIPTION
**Pull request by Undin**
These changes allow parsing mod items with `unsafe` keyword to be consistent with rustc (see https://github.com/rust-lang/rust/pull/75857/) and annotate `unsafe` keyword as an error in such cases on the semantic level.

image

Note, the corresponding change in rustc was made mainly to provide token tree to proc macros where `unsafe` keyword should be handled by proc macro itself. And in case of such proc macro, `unsafe` keyword shouldn't be annotated as an error. But after these changes, `unsafe` will be annotated as an error by the plugin. But it doesn't look like a new issue, since previously it was annotated as parser error.

For example, for the following code
```rust
//- lib.rs
use proc_macro::TokenStream;
use std::str::FromStr;

#[proc_macro_attribute]
pub fn my_attr(_attr: TokenStream, _item: TokenStream) -> TokenStream {
    return TokenStream::from_str("pub fn foo() { println!(\"Hello from macro!\")}").unwrap()
}

//- main.rs
#[rust_project::my_attr]
unsafe mod foo {}

fn main() {
    foo();
}
```

the plugin produces the corresponding annotations
| Before | After |
| - | - |
| image | image |

Proper support for error annotations of such cases should be implemented separately, not only for `unsafe` keyword in modules and requires changes from #7194

changelog: Parse `unsafe` keyword in modules and provide error annotation for it

### CODE REVIEW

**Comment by Undin** [comment]
Interesting fact: our parser tests didn't contain any test with module declaration before these changes

**Review by vlad20012 — APPROVED** [review]
:+1: 
bors r+

**Comment by Undin** [comment]
bors retry

**Comment by Undin** [comment]
bors r=vlad20012

**Pull request merged**
