### PR TITLE
T: Show test result in the gutter

### PR DESCRIPTION
**Pull request by mchernyavsky**
Fixes https://github.com/intellij-rust/intellij-rust/issues/6175.

### CODE REVIEW

**Review by mchernyavsky — COMMENTED** [review]
bors r+

**Review by Undin — COMMENTED** [review]
@mchernyavsky Is it possible to write tests for the corresponding feature?
Note, we already have some tests for line markers

**Comment by mchernyavsky** [comment]
@Undin We already have tests for this feature (in `CargoTestRunLineMarkerContributorTest`), but they don't help really.

**Comment by Undin** [comment]
@mchernyavsky but these tests are about providing some icon to run tests but they don't check a kind of icon

**Comment by mchernyavsky** [comment]
@Undin see
* `ttest show a green mark for a passed test`
* `test show a red mark for a failed test`
* `test show a mark for an ignored test`
* `test show a green mark for a passed mod`
* `test show a red mark for a failed mod`
* `test show a mark for an ignored mod`

**Comment by Undin** [comment]
@mchernyavsky Oh, I see.
But looks like these tests really check nothing because we manually write status into `TestStateStorage`. Do they actually make sense? Maybe it's better to run tests and check statuses after that?

**Pull request merged**
