### PR TITLE
CI: Test WSL toolchains on CI

### PR DESCRIPTION
**Pull request by mchernyavsky**
Closes https://github.com/intellij-rust/intellij-rust/issues/7195.

### CODE REVIEW

**Comment by ssbarnea** [comment]
@mchernyavsky Out of curiosity, what is your current take regarding WSL support on GHA? I am asking this because I need do find a working way to make use of WSL for another project where on WSL would work. Seen a project that correctly makes use of WSL in GHA could of a great help.

**Review by ssbarnea — CHANGES_REQUESTED** [review]
It might me my job but this approach is guaranteed to break as soon github upgrades the runner, and that happens quite often and without notice.

**Comment by mchernyavsky** [comment]
@ssbarnea Looks like the workflow is not hanging since Rust 1.64.0, so I'm not sure that the problem is related to the runner.

**Comment by ssbarnea** [comment]
> @ssbarnea Looks like the workflow is not hanging since Rust 1.64.0, so I'm not sure that the problem is related to the runner.

My only concern is related to use of a full path `C:\hostedtoolcache\windows\Ubuntu\20.4.0\x64\ubuntu.exe` which is high likely to break when Github will refresh their container image. They do this often, updating the hostedtoolcache and that is not really announced. I think that we should determine the path instead to make the pipeline more resilient.

**Comment by mchernyavsky** [comment]
> Looks like the workflow is not hanging since Rust 1.64.0

No, it doesn't work :(

> I think that we should determine the path instead to make the pipeline more resilient.

I haven't tested it, but probably you could do this to change default user:

```
- name: Set up WSL
  uses: Vampire/setup-wsl@v1
  with:
      distribution: Ubuntu-20.04
      wsl-shell-user: test
      wsl-conf: |
          [user]
          default = test
```

**Pull request closed without merging**
