### PR TITLE
INT: add support for generic types to unelide lifetimes intention

### PR DESCRIPTION
**Pull request by Kobzol**
This PR generalizes the Unelide lifetimes intention to work with generic types.

Fixes: https://github.com/intellij-rust/intellij-rust/issues/769

### CODE REVIEW

**Comment by Kobzol** [comment]
What about nested liftimes?

For example with this fn:
`fn make_s<'a>(x: &'a S<'a>) { }`
elision is not offered by the plugin, does that mean that for
`fn make_s(x: &S) { }`
it should not offer to unelide?
What should be the general rule, that there is only one lifetime and no nested ones?

**Comment by Kobzol** [comment]
I pushed an initial version of unelision which tries to be more general. Requesting feedback :-)

This now works:
```rust
struct S<'a, T, X> { x: &'a T, y: X }
fn make_s<X>(x: S<u32, X>) -> S<u32, X> { unimplemented!() }
fn make_s<'a, X>(x: S<'a, u32, X>) -> S<'a, u32, X> { unimplemented!() }
```

Howver, it is not recursive yet, i.e. it does not handle nested types.
Should this also work or should we stop trying at some point?
```rust
trait S<'a, T>
{
    type N;
    fn foo(&self, a: &'a u32, b: T, c: Self::N);
}
fn make_s(x: Box<dyn S<u32, N=u32>>) -> Box<dyn S<u32, N=u32>> { unimplemented!() }
fn make_s<'a>(x: Box<dyn S<'a, u32, N=u32>>) -> Box<dyn S<'a, u32, N=u32>> { unimplemented!() }
```

**Comment by Kobzol** [comment]
I updated the PR and rebased it onto master. I will handle impl block unelision in a different PR. The intention is still not recursive, as mentioned in the previous comments, but I'm not sure if that's a good idea. What do you think?

**Comment by Kobzol** [comment]
@mchernyavsky ping

**Comment by Kobzol** [comment]
Rebased to fix merge conflict.

**Review by mchernyavsky — COMMENTED** [review]
> I updated the PR and rebased it onto master. I will handle impl block unelision in a different PR. The intention is still not recursive, as mentioned in the previous comments, but I'm not sure if that's a good idea. What do you think?

I agree, but what about ADTs with multiple lifetimes? I think we shouldn't close https://github.com/intellij-rust/intellij-rust/issues/769 until this case is supported.

**Comment by Kobzol** [comment]
I added support for multiple lifetime arguments for structs in parameters. I'm not sure what should be the semantics for the output type though.
```rust
struct S<'a, 'b> { x: &'a u32, y: &'b u32 }
fn make_s<'a, 'b>(x:/*caret*/ &'a i32) -> S<'a, 'b> { unimplemented!() }
```
I'm not even sure if this qualifies as (un)elision.

**Comment by mchernyavsky** [comment]
> I added support for multiple lifetime arguments for structs in parameters. I'm not sure what should be the semantics for the output type though.

I think the intention shouldn't be available in such cases. If I'm not mistaken, in all other cases the result can be reverted with the `Elide lifetimes` fix.

**Comment by Kobzol** [comment]
> I think the intention shouldn't be available in such cases. If I'm not mistaken, in all other cases the result can be reverted with the `Elide lifetimes` fix.

Good point. To mirror `RsNeedlessLifetimesInspection`, I now do not offer the intention if the output has multiple lifetimes.

**Review by mchernyavsky — APPROVED** [review]
Thanks!

bors r+

**Pull request merged**
