### PR TITLE
REF: handle name conflicts after renaming bindings

### PR DESCRIPTION
**Pull request by Kobzol**
This PR adds support for detecting conflicts that can arise when bindings are renamed. The behaviour is inspired by the Kotlin/Java plugin, however I also added support for conflicts during renaming parameters (this doesn't happen in Kotlin/Java). I'm not sure if it's a good idea though.

The implementation uses `processLocalVariables` to find local bindings, so it only "sees" existing names that are available at the place of the binding which is being renamed.

```rust
fn test() {
    let c/*rename to a*/ = 1;  // no conflict
    let a = 1;
    let b/*rename to a*/ = 1;  // conflict
}
```
I'm not sure what's the best behaviour here. Renaming `c` to `a` should be fine, but only if there is no usage of `c` that follows the declaration of the previous `a` binding. To support this scenario we would have to scan the usages of local variables and only include the conflict if `X` is renamed to `Y` and a usage of `X` "crosses" a declaration of another binding with name `Y`. Or we can do it like Kotlin and simply process all local bindings in the scope (i.e. go both up and down), which might be simpler. It would also be easier for parameter handling, currently I scan the function from the end for local variables, but it does not take bindings that are the last child of a block/function into account because they do not "see" themselves when `processLocalVariables` is used. 

The line `error("Conflicts $conflicts missing")` in tests is not practically reachable, because if there are no conflicts the refactoring will proceed and the test will fail with a `ComparisonFailure`, which I did not know how to handle/catch.

Fixes: https://github.com/intellij-rust/intellij-rust/issues/3630

### CODE REVIEW

**Comment by vlad20012** [comment]
:+1: 
bors r+

> Or we can do it like Kotlin and simply process all local bindings in the scope (i.e. go both up and down), which might be simpler. 

Well, why not? :shrug: Sounds better than current behavior. It can be a bit tricky to distinguish scopes where the renaming binding is reachable.
```rust
fn foo() {
    {
        let a = 1; // not reachable
        let b/*caret*/ = 1; // rename to a
        {
            let a = 1; // conflict
        }
    }
    let a = 1; // not reachable
}
```

Looks like we can collect binding in `b`'s parent scope and then filter binding below `b` using text offsets =D

**Comment by vlad20012** [comment]
bors retry

**Comment by Kobzol** [comment]
I'm a bit confused, so should I change the current behaviour? :D

**Comment by vlad20012** [comment]
> I'm a bit confused, so should I change the current behaviour? :D

1. This merged PR is much better than old behavior (thanks!).
2. Looks like it's possible to improve it a bit more.

So, you _may_, if you wish. As usual 😃

**Pull request merged**
