### PR TITLE
(ANN) Implemented chain comparison annotation (ERROR 0308)

### PR DESCRIPTION
**Pull request by la10736**

### CODE REVIEW

**Comment by matklad** [comment]
Sorry for the merge conflict: I am doing some **massive** refactoring of our tokens / grammar :(

Will finish later today, so don't rush rebasing :)

**Comment by alygin** [comment]
I think [E0308](https://doc.rust-lang.org/error-index.html#E0308) is all about type mismatchings and inability to infer types. It occurs in the provided tests just because a) `x` is not declared in the first comparison, and b) even it it was declared, it would be boolean vs integer in the second comparison.

In this code:

```rust
let x = 10;
1 < x < 3
```

`rustc` emits the following errors:

```
error: chained comparison operators require parentheses
  --> src/main.rs:59:11
   |
59 |         1 < x < 3
   |           ^^^^^^^

error[E0308]: mismatched types
  --> src/main.rs:59:17
   |
59 |         1 < x < 3
   |                 ^ expected bool, found integral variable
   |
   = note: expected type `bool`
   = note:    found type `{integer}`

error[E0308]: mismatched types
  --> src/main.rs:59:9
   |
59 |         1 < x < 3
   |         ^^^^^^^^^ expected (), found bool
   |
   = note: expected type `()`
   = note:    found type `bool`
```

Here, both the E0308 errors are about type mismatching, while the first one is about chained comparison and it has no personal error code so far.

**Comment by matklad** [comment]
Yep, @alygin is right! To get the pure form of the error, the following code is needed:

```
let _ = true == true == true;
```

```
error: chained comparison operators require parentheses
 --> main.rs:2:18
  |
2 |     let _ = true == true == true;
  |                  ^^^^^^^^^^^^^^^
```

**Comment by la10736** [comment]
Thank you very much for the prompt feedback. I'll rewriting by raise 498 error and make a new PR based on your refactoring next days.

**Comment by matklad** [comment]
Refactoring is finished!

**Comment by matklad** [comment]
token sets now live alongside the `RsTokenType`.

**Comment by matklad** [comment]
I think this can be closed because #945  is merged!

**Comment by matklad** [comment]
>I think this can be closed because #945 is merged!

Wait, I have not merged it yet, :crying_cat_face: , fixing ASAP. Thanks @la10736 !

**Pull request closed without merging**
