### PR TITLE
(COMPLETION): initial

### PR DESCRIPTION
**Pull request by matklad**
Ok, here is the second take on the completion :)

@alexeykudinkin @atsky please review.

I don't like that this don't respect scope of locals and thus gives false positives. However I don't see how this can be fixed without duplicating scope visitor and without introducing something like processors from #196 

But this is still much better then nothing :)

### CODE REVIEW

**Comment by alexeykudinkin** [comment]
Just to make a stress: we can (and more than that, we _should_) have a scope-processor for the completion purposes. But. 

It should NOT be a part of the `RustResolveEngine` though it may seem they look 'similar', they do indeed, but them should not be interleaved with each other.

**Comment by matklad** [comment]
Ok, will add a scope processor here. Or may be we can merge this and a processor will be a separate PR

**Comment by alexeykudinkin** [comment]
I believe we'd rather use this P/R as a magnet for the all completion-related changes, and it'd be better to merge the whole feature upon it being deemed complete.

**Comment by matklad** [comment]
@alexeykudinkin updated

**Comment by alexeykudinkin** [comment]
Awesome! Thanks!

**Pull request merged**
